/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmCertificate.java
 *
 * Created on Mar 22, 2011, 9:25:46 PM
 */
package com.hueic.CerGS.ui.main.report;

import com.hueic.CerGS.component.report.CertificateReportManager;
import com.hueic.CerGS.dao.CertificateDAO;
import com.hueic.CerGS.dao.MarkDAO;
import com.hueic.CerGS.dao.RegisterDAO;
import com.hueic.CerGS.entity.Certificate;

/**
 *
 * @author Wind
 */
public class frmCertificate extends javax.swing.JFrame {

    private int certificateId;
    private String courseId;
    
    private MarkDAO markDAO;
    private RegisterDAO registerDAO;
    private CertificateDAO cerDAO;
    private Certificate cer;
    
    private CertificateReportManager cerReportManager;

    /** Creates new form frmCertificate */
    public frmCertificate(int certificateId) {
        initComponents();
        this.certificateId = certificateId;
        registerDAO = new RegisterDAO();
        cerDAO = new CertificateDAO();
        cer = cerDAO.readById(this.certificateId);
        markDAO = new MarkDAO();

        courseId = registerDAO.readByStudentId(cer.getStudentID()).getCourseId();

        cerReportManager = new CertificateReportManager(cer.getStudentID(), courseId, cer.getDegreeDay(), markDAO.getGrades(cer.getMark()));

        this.add(cerReportManager.getJPanelViewer());
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                //new frmCertificate().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
