/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrm.java
 *
 * Created on Mar 13, 2011, 5:37:51 PM
 */
package com.hueic.CerGS.ui.main;

import com.hueic.CerGS.entity.Account;
import com.hueic.CerGS.ui.system.frmLogin;
import com.hueic.CerGS.ui.system.frmAbout;
import com.hueic.CerGS.component.GUIProperties;
import com.hueic.CerGS.dao.GUIDAO;
import com.hueic.CerGS.ui.main.employee.frmEmployee;
import com.hueic.CerGS.ui.main.student.frmStudent;
import com.hueic.CerGS.ui.system.frmChangePass;
import java.net.URL;
import javax.help.CSH;
import javax.help.HelpBroker;
import javax.help.HelpSet;

/**
 *
 * @author nhchung
 */
public class frmMain extends javax.swing.JFrame {

    /** Creates new form MainFrm */
    GUIDAO guidao = null;
    GUIProperties guip = null;
    public Account accCur;

    public frmMain() {
        initComponents();
        setLocationRelativeTo(null);
        guidao = new GUIDAO(this);
        guip = new GUIProperties();
        guidao.setGUI(guip.PLAF_JGOODIES);
        bindingLang();
        setSize(1100, 700);
        HelpSet hs = getHelpSet("com/hueic/CerGS/myhelp/sample.hs");
        HelpBroker hb = hs.createHelpBroker();

        // 2. assign help to components
        CSH.setHelpIDString(mnuIHelpContent, "top");
        mnuIHelpContent.addActionListener(new CSH.DisplayHelpFromSource(hb));
    }

    public HelpSet getHelpSet(String helpsetfile) {
        HelpSet hs = null;
        ClassLoader cl = this.getClass().getClassLoader();
        try {
            URL hsURL = HelpSet.findHelpSet(cl, helpsetfile);
            hs = new HelpSet(null, hsURL);
        } catch (Exception ee) {
            System.out.println("HelpSet: " + ee.getMessage());
            System.out.println("HelpSet: " + helpsetfile + " not found");
        }
        return hs;
    }

    public void bindingLang() {
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupLanguage = new javax.swing.ButtonGroup();
        buttonGroupSkin = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jTaskPane1 = new com.l2fprod.common.swing.JTaskPane();
        jTaskPaneGroupManagementStudent = new com.l2fprod.common.swing.JTaskPaneGroup();
        jTaskPaneGroupManagementEmployee = new com.l2fprod.common.swing.JTaskPaneGroup();
        jTaskPaneGroup3 = new com.l2fprod.common.swing.JTaskPaneGroup();
        jTaskPaneGroup4 = new com.l2fprod.common.swing.JTaskPaneGroup();
        jTaskPaneGroup5 = new com.l2fprod.common.swing.JTaskPaneGroup();
        jTaskPaneGroup6 = new com.l2fprod.common.swing.JTaskPaneGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mnuBSystem = new javax.swing.JMenuBar();
        mnuSystem = new javax.swing.JMenu();
        menuIChangePass = new javax.swing.JMenuItem();
        mnuILoginSystem = new javax.swing.JMenuItem();
        mnuIViewInformation = new javax.swing.JMenuItem();
        mnuISwitchUser = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuIExit = new javax.swing.JMenuItem();
        mnuAdministrator = new javax.swing.JMenu();
        mnuIManagementStudent = new javax.swing.JMenuItem();
        mnuEmployee = new javax.swing.JMenu();
        mnuIManagmentEmp = new javax.swing.JMenuItem();
        mnuStudent = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        radioVietnamese = new javax.swing.JRadioButtonMenuItem();
        radioEnglish = new javax.swing.JRadioButtonMenuItem();
        radioJapan = new javax.swing.JRadioButtonMenuItem();
        radioChina = new javax.swing.JRadioButtonMenuItem();
        radioPhap = new javax.swing.JRadioButtonMenuItem();
        jMenu3 = new javax.swing.JMenu();
        radioWindows = new javax.swing.JRadioButtonMenuItem();
        radioMetal = new javax.swing.JRadioButtonMenuItem();
        radioNimbus = new javax.swing.JRadioButtonMenuItem();
        radioMotif = new javax.swing.JRadioButtonMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mnuIHelpContent = new javax.swing.JMenuItem();
        mnuIAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Certificate Generation System");
        setResizable(false);

        jTaskPaneGroupManagementStudent.setTitle("Management Student");
        jTaskPane1.add(jTaskPaneGroupManagementStudent);

        jTaskPaneGroupManagementEmployee.setTitle("Management Employee");
        jTaskPaneGroupManagementEmployee.setToolTipText("Management Employee");
        jTaskPane1.add(jTaskPaneGroupManagementEmployee);
        jTaskPane1.add(jTaskPaneGroup3);
        jTaskPane1.add(jTaskPaneGroup4);
        jTaskPane1.add(jTaskPaneGroup5);

        jTaskPaneGroup6.setTitle("Management Report");
        jTaskPaneGroup6.setToolTipText("Management Report");
        jTaskPane1.add(jTaskPaneGroup6);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/Dollar.png"))); // NOI18N

        jLabel3.setText("Test thu");

        jLabel4.setText("Test thu");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/Dollar.png"))); // NOI18N

        jLabel6.setText("Test thu");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/Dollar.png"))); // NOI18N

        jLabel8.setText("Test thu");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/Dollar.png"))); // NOI18N

        jLabel10.setText("Test thu");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/Dollar.png"))); // NOI18N

        jLabel12.setText("Test thu");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/Dollar.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(106, 106, 106))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel3))
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel4))
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel6)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel12))
                            .addComponent(jLabel13)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel10))
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel8)))
                .addContainerGap(249, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/banner copy.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mnuSystem.setText("System");

        menuIChangePass.setText("Change Pass");
        menuIChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIChangePassActionPerformed(evt);
            }
        });
        mnuSystem.add(menuIChangePass);

        mnuILoginSystem.setText("Login System");
        mnuILoginSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuILoginSystemActionPerformed(evt);
            }
        });
        mnuSystem.add(mnuILoginSystem);

        mnuIViewInformation.setText("View Information");
        mnuSystem.add(mnuIViewInformation);

        mnuISwitchUser.setText("Switch User");
        mnuSystem.add(mnuISwitchUser);
        mnuSystem.add(jSeparator1);

        mnuIExit.setText("Exit");
        mnuIExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIExitActionPerformed(evt);
            }
        });
        mnuSystem.add(mnuIExit);

        mnuBSystem.add(mnuSystem);

        mnuAdministrator.setText("Student");

        mnuIManagementStudent.setText("Management Student");
        mnuIManagementStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIManagementStudentActionPerformed(evt);
            }
        });
        mnuAdministrator.add(mnuIManagementStudent);

        mnuBSystem.add(mnuAdministrator);

        mnuEmployee.setText("Employe");

        mnuIManagmentEmp.setText("Management Employee");
        mnuIManagmentEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIManagmentEmpActionPerformed1(evt);
            }
        });
        mnuEmployee.add(mnuIManagmentEmp);

        mnuBSystem.add(mnuEmployee);

        mnuStudent.setText("Payment");
        mnuBSystem.add(mnuStudent);

        jMenu1.setText("Option");

        jMenu2.setText("Language");

        buttonGroupLanguage.add(radioVietnamese);
        radioVietnamese.setSelected(true);
        radioVietnamese.setText("Vietnamese");
        jMenu2.add(radioVietnamese);

        buttonGroupLanguage.add(radioEnglish);
        radioEnglish.setText("English");
        jMenu2.add(radioEnglish);

        buttonGroupLanguage.add(radioJapan);
        radioJapan.setText("Japan");
        jMenu2.add(radioJapan);

        buttonGroupLanguage.add(radioChina);
        radioChina.setText("China");
        jMenu2.add(radioChina);

        buttonGroupLanguage.add(radioPhap);
        radioPhap.setText("Phap");
        jMenu2.add(radioPhap);

        jMenu1.add(jMenu2);

        jMenu3.setText("Skin");

        buttonGroupSkin.add(radioWindows);
        radioWindows.setSelected(true);
        radioWindows.setText("Windows");
        radioWindows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioWindowsActionPerformed(evt);
            }
        });
        jMenu3.add(radioWindows);

        buttonGroupSkin.add(radioMetal);
        radioMetal.setText("Metal");
        radioMetal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMetalActionPerformed(evt);
            }
        });
        jMenu3.add(radioMetal);

        buttonGroupSkin.add(radioNimbus);
        radioNimbus.setText("Nimbus");
        radioNimbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNimbusActionPerformed(evt);
            }
        });
        jMenu3.add(radioNimbus);

        buttonGroupSkin.add(radioMotif);
        radioMotif.setText("Motif");
        radioMotif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMotifActionPerformed(evt);
            }
        });
        jMenu3.add(radioMotif);

        jMenu1.add(jMenu3);

        mnuBSystem.add(jMenu1);

        mnuHelp.setText("Help");

        mnuIHelpContent.setText("Help Contents");
        mnuIHelpContent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIHelpContentActionPerformed(evt);
            }
        });
        mnuHelp.add(mnuIHelpContent);

        mnuIAbout.setText("About");
        mnuIAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIAboutActionPerformed(evt);
            }
        });
        mnuHelp.add(mnuIAbout);

        mnuBSystem.add(mnuHelp);

        setJMenuBar(mnuBSystem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTaskPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTaskPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuILoginSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuILoginSystemActionPerformed
        // TODO add your handling code here:
        frmLogin login = new frmLogin();
        login.setVisible(true);
    }//GEN-LAST:event_mnuILoginSystemActionPerformed

    private void mnuIAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIAboutActionPerformed
        // TODO add your handling code here:
        frmAbout about = new frmAbout();
        about.setVisible(true);
    }//GEN-LAST:event_mnuIAboutActionPerformed

    private void radioWindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioWindowsActionPerformed
        // TODO add your handling code here:
        if (radioWindows.isSelected()) {
            guidao.setGUI(guip.PLAF_WINDOWS);
        }
    }//GEN-LAST:event_radioWindowsActionPerformed

    private void radioMetalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMetalActionPerformed
        // TODO add your handling code here:
        if (radioMetal.isSelected()) {
            guidao.setGUI(guip.PLAF_METAL);
        }
    }//GEN-LAST:event_radioMetalActionPerformed

    private void radioNimbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNimbusActionPerformed
        // TODO add your handling code here:
        if (radioNimbus.isSelected()) {
            guidao.setGUI(guip.PLAF_NIMBUS);
        }
    }//GEN-LAST:event_radioNimbusActionPerformed

    private void radioMotifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMotifActionPerformed
        // TODO add your handling code here:
        if (radioMotif.isSelected()) {
            guidao.setGUI(guip.PLAF_MOTIF);
        }
    }//GEN-LAST:event_radioMotifActionPerformed

    private void menuIChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIChangePassActionPerformed
        // TODO add your handling code here:
        frmChangePass changePass = new frmChangePass();
        changePass.setVisible(true);
    }//GEN-LAST:event_menuIChangePassActionPerformed

    private void mnuIManagmentEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIManagmentEmpActionPerformed
        // TODO add your handling code here:
        frmEmployee employee = new frmEmployee();
        employee.setVisible(true);
    }//GEN-LAST:event_mnuIManagmentEmpActionPerformed

    private void mnuIHelpContentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIHelpContentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuIHelpContentActionPerformed

    private void mnuIExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mnuIExitActionPerformed

    private void mnuIManagementStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIManagementStudentActionPerformed
        // TODO add your handling code here:
        frmStudent student = new frmStudent();
        student.setVisible(true);
    }//GEN-LAST:event_mnuIManagementStudentActionPerformed

    private void mnuIManagmentEmpActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIManagmentEmpActionPerformed1
        // TODO add your handling code here:
        frmEmployee employee = new frmEmployee();
        employee.setVisible(true);
    }//GEN-LAST:event_mnuIManagmentEmpActionPerformed1

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupLanguage;
    private javax.swing.ButtonGroup buttonGroupSkin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private com.l2fprod.common.swing.JTaskPane jTaskPane1;
    private com.l2fprod.common.swing.JTaskPaneGroup jTaskPaneGroup3;
    private com.l2fprod.common.swing.JTaskPaneGroup jTaskPaneGroup4;
    private com.l2fprod.common.swing.JTaskPaneGroup jTaskPaneGroup5;
    private com.l2fprod.common.swing.JTaskPaneGroup jTaskPaneGroup6;
    private com.l2fprod.common.swing.JTaskPaneGroup jTaskPaneGroupManagementEmployee;
    private com.l2fprod.common.swing.JTaskPaneGroup jTaskPaneGroupManagementStudent;
    private javax.swing.JMenuItem menuIChangePass;
    private javax.swing.JMenu mnuAdministrator;
    private javax.swing.JMenuBar mnuBSystem;
    private javax.swing.JMenu mnuEmployee;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenuItem mnuIAbout;
    private javax.swing.JMenuItem mnuIExit;
    private javax.swing.JMenuItem mnuIHelpContent;
    private javax.swing.JMenuItem mnuILoginSystem;
    private javax.swing.JMenuItem mnuIManagementStudent;
    private javax.swing.JMenuItem mnuIManagmentEmp;
    private javax.swing.JMenuItem mnuISwitchUser;
    private javax.swing.JMenuItem mnuIViewInformation;
    private javax.swing.JMenu mnuStudent;
    private javax.swing.JMenu mnuSystem;
    private javax.swing.JRadioButtonMenuItem radioChina;
    private javax.swing.JRadioButtonMenuItem radioEnglish;
    private javax.swing.JRadioButtonMenuItem radioJapan;
    private javax.swing.JRadioButtonMenuItem radioMetal;
    private javax.swing.JRadioButtonMenuItem radioMotif;
    private javax.swing.JRadioButtonMenuItem radioNimbus;
    private javax.swing.JRadioButtonMenuItem radioPhap;
    private javax.swing.JRadioButtonMenuItem radioVietnamese;
    private javax.swing.JRadioButtonMenuItem radioWindows;
    // End of variables declaration//GEN-END:variables
}
