/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrm.java
 *
 * Created on Mar 13, 2011, 5:37:51 PM
 */
package com.hueic.CerGS.ui;

import com.hueic.CerGS.component.AppStatusBar;
import com.hueic.CerGS.entity.Account;
import com.hueic.CerGS.component.GUIProperties;
import com.hueic.CerGS.component.IconSystem;
import com.hueic.CerGS.dao.GUIDAO;
import com.hueic.CerGS.dao.PermissionDAO;
import java.net.URL;
import javax.help.CSH;
import javax.help.HelpBroker;
import javax.help.HelpSet;

/**
 *
 * @author nhchung
 */
public class frmMain extends javax.swing.JFrame {

    /** Creates new form MainFrm */
    GUIDAO guidao = null;
    GUIProperties guip = new GUIProperties();
    public Account accCur;
    String theme = "Silver";
    String lookandfeel = guip.PLAF_JGOODIES;
    pnlAccount account = new pnlAccount();
    pnlCertificate cer = new pnlCertificate(this);
    pnlCourse course = new pnlCourse(this);
    pnlMark mark = new pnlMark(this);
    pnlPayment payment = new pnlPayment(this);
    pnlRegister register = new pnlRegister(this);
    pnlPermission per = new pnlPermission();
    pnlSubject subject = new pnlSubject(this);
    pnlStudent student = new pnlStudent(this);
    pnlEmployee emp = new pnlEmployee(this);
    pnlViewMark viewMark = new pnlViewMark(this);
    pnlViewPayment viewPayment = new pnlViewPayment(this);
    pnlDevelopDegree developDegree = new pnlDevelopDegree(this);
    pnlHome homeAdmin = new pnlHome(this);
    pnlReport report = new pnlReport();
    PermissionDAO perDao;

    public frmMain() {
        initComponents();
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        perDao = new PermissionDAO();
        guidao = new GUIDAO(this);
        guidao.setGUI(lookandfeel, theme);
        new IconSystem(this);
        initStatusBar();
        HelpSet hs = getHelpSet("com/hueic/CerGS/myhelp/sample.hs");
        HelpBroker hb = hs.createHelpBroker();
        CSH.setHelpIDString(mnuIHelpContent, "top");
        mnuIHelpContent.addActionListener(new CSH.DisplayHelpFromSource(hb));
    }

    private void initStatusBar() {
        AppStatusBar status = new AppStatusBar();
        this.StatusPnl.add(status.getBar());
    }

    public HelpSet getHelpSet(String helpsetfile) {
        HelpSet hs = null;
        ClassLoader cl = this.getClass().getClassLoader();
        try {
            URL hsURL = HelpSet.findHelpSet(cl, helpsetfile);
            hs = new HelpSet(null, hsURL);
        } catch (Exception ee) {
            System.out.println("HelpSet: " + ee.getMessage());
            System.out.println("HelpSet: " + helpsetfile + " not found");
        }
        return hs;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroupSkin = new javax.swing.ButtonGroup();
        buttonGroupTheme = new javax.swing.ButtonGroup();
        panelLogo = new javax.swing.JPanel();
        tbMenu = new javax.swing.JToolBar();
        jideBtnHome = new com.jidesoft.swing.JideButton();
        jideBtnEmployee = new com.jidesoft.swing.JideButton();
        jideBtnStudent = new com.jidesoft.swing.JideButton();
        jideBtnRegister = new com.jidesoft.swing.JideButton();
        jideBtnCourse = new com.jidesoft.swing.JideButton();
        jideBtnSubject = new com.jidesoft.swing.JideButton();
        jideBtnCertificate = new com.jidesoft.swing.JideButton();
        jideBtnAccount = new com.jidesoft.swing.JideButton();
        jideBtnMark = new com.jidesoft.swing.JideButton();
        jideBtnPayment = new com.jidesoft.swing.JideButton();
        jideBtnReport = new com.jidesoft.swing.JideButton();
        panelLeft = new javax.swing.JPanel();
        tpnBusiness = new javax.swing.JTabbedPane();
        pnlHome = new javax.swing.JPanel();
        pnlEmployee = new javax.swing.JPanel();
        pnlStudent = new javax.swing.JPanel();
        pnlRegister = new javax.swing.JPanel();
        pnlCourse = new javax.swing.JPanel();
        pnlPayment = new javax.swing.JPanel();
        pnlSubject = new javax.swing.JPanel();
        pnlMark = new javax.swing.JPanel();
        pnlCertificate = new javax.swing.JPanel();
        pnlAccount = new javax.swing.JPanel();
        pnlPermission = new javax.swing.JPanel();
        pnlViewMark = new javax.swing.JPanel();
        pnlViewPayment = new javax.swing.JPanel();
        pnlDevelopDegree = new javax.swing.JPanel();
        pnlReport = new javax.swing.JPanel();
        StatusPnl = new javax.swing.JPanel();
        mnuBSystem = new javax.swing.JMenuBar();
        mnuSystem = new javax.swing.JMenu();
        mnuILoginSystem = new javax.swing.JMenuItem();
        mnuILogoutSystem = new javax.swing.JMenuItem();
        menuIChangePass = new javax.swing.JMenuItem();
        mnuIConfiguration = new javax.swing.JMenuItem();
        mnuOptions = new javax.swing.JMenu();
        mnuSkin = new javax.swing.JMenu();
        radioWindows = new javax.swing.JRadioButtonMenuItem();
        radioMetal = new javax.swing.JRadioButtonMenuItem();
        radioNimbus = new javax.swing.JRadioButtonMenuItem();
        radioJgoodies = new javax.swing.JRadioButtonMenuItem();
        mnuTheme = new javax.swing.JMenu();
        radioDarkStar = new javax.swing.JRadioButtonMenuItem();
        radioDesertBlue = new javax.swing.JRadioButtonMenuItem();
        radioDesertGreen = new javax.swing.JRadioButtonMenuItem();
        radioDesertYellow = new javax.swing.JRadioButtonMenuItem();
        radioExperienceBlue = new javax.swing.JRadioButtonMenuItem();
        radioExperienceGreen = new javax.swing.JRadioButtonMenuItem();
        radioExperenceRoyale = new javax.swing.JRadioButtonMenuItem();
        radioLightGray = new javax.swing.JRadioButtonMenuItem();
        radioSilver = new javax.swing.JRadioButtonMenuItem();
        radioSkyBlue = new javax.swing.JRadioButtonMenuItem();
        radioSkyBluer = new javax.swing.JRadioButtonMenuItem();
        radioSkyGreen = new javax.swing.JRadioButtonMenuItem();
        radioSkyPink = new javax.swing.JRadioButtonMenuItem();
        radioSkyRed = new javax.swing.JRadioButtonMenuItem();
        radioSkyYellow = new javax.swing.JRadioButtonMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuIExit = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mnuIHelpContent = new javax.swing.JMenuItem();
        mnuIAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Certificate Generation System");
        setMinimumSize(new java.awt.Dimension(1000, 720));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panelLogo.setMinimumSize(new java.awt.Dimension(1024, 40));
        panelLogo.setPreferredSize(new java.awt.Dimension(1024, 40));
        panelLogo.setLayout(new java.awt.GridBagLayout());

        tbMenu.setFloatable(false);
        tbMenu.setRollover(true);
        tbMenu.setMaximumSize(new java.awt.Dimension(1024, 40));
        tbMenu.setMinimumSize(new java.awt.Dimension(1024, 40));
        tbMenu.setPreferredSize(new java.awt.Dimension(1024, 40));

        jideBtnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/home_icon.png"))); // NOI18N
        jideBtnHome.setToolTipText("Home");
        jideBtnHome.setEnabled(false);
        jideBtnHome.setFocusable(false);
        jideBtnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jideBtnHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jideBtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jideBtnHomeActionPerformed(evt);
            }
        });
        tbMenu.add(jideBtnHome);

        jideBtnEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/emp_icon_32.png"))); // NOI18N
        jideBtnEmployee.setToolTipText("Manager Employee");
        jideBtnEmployee.setEnabled(false);
        jideBtnEmployee.setFocusable(false);
        jideBtnEmployee.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jideBtnEmployee.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jideBtnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jideBtnEmployeeActionPerformed(evt);
            }
        });
        tbMenu.add(jideBtnEmployee);

        jideBtnStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/student_icon -32.png"))); // NOI18N
        jideBtnStudent.setToolTipText("Manager Student");
        jideBtnStudent.setEnabled(false);
        jideBtnStudent.setFocusable(false);
        jideBtnStudent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jideBtnStudent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jideBtnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jideBtnStudentActionPerformed(evt);
            }
        });
        tbMenu.add(jideBtnStudent);

        jideBtnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/icon_register.png"))); // NOI18N
        jideBtnRegister.setToolTipText("Manager Register");
        jideBtnRegister.setEnabled(false);
        jideBtnRegister.setFocusable(false);
        jideBtnRegister.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jideBtnRegister.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jideBtnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jideBtnRegisterActionPerformed(evt);
            }
        });
        tbMenu.add(jideBtnRegister);

        jideBtnCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/icon_course.png"))); // NOI18N
        jideBtnCourse.setToolTipText("Manager Course");
        jideBtnCourse.setEnabled(false);
        jideBtnCourse.setFocusable(false);
        jideBtnCourse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jideBtnCourse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jideBtnCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jideBtnCourseActionPerformed(evt);
            }
        });
        tbMenu.add(jideBtnCourse);

        jideBtnSubject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/subject_icon.png"))); // NOI18N
        jideBtnSubject.setToolTipText("Manager Subject");
        jideBtnSubject.setEnabled(false);
        jideBtnSubject.setFocusable(false);
        jideBtnSubject.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jideBtnSubject.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jideBtnSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jideBtnSubjectActionPerformed(evt);
            }
        });
        tbMenu.add(jideBtnSubject);

        jideBtnCertificate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/Certificate_icon_32.png"))); // NOI18N
        jideBtnCertificate.setToolTipText("Manager Certificate");
        jideBtnCertificate.setEnabled(false);
        jideBtnCertificate.setFocusable(false);
        jideBtnCertificate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jideBtnCertificate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jideBtnCertificate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jideBtnCertificateActionPerformed(evt);
            }
        });
        tbMenu.add(jideBtnCertificate);

        jideBtnAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/account_icon -32.png"))); // NOI18N
        jideBtnAccount.setToolTipText("Manager Account");
        jideBtnAccount.setEnabled(false);
        jideBtnAccount.setFocusable(false);
        jideBtnAccount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jideBtnAccount.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jideBtnAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jideBtnAccountActionPerformed(evt);
            }
        });
        tbMenu.add(jideBtnAccount);

        jideBtnMark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/mark_icon_32.png"))); // NOI18N
        jideBtnMark.setToolTipText("Manager Mark");
        jideBtnMark.setEnabled(false);
        jideBtnMark.setFocusable(false);
        jideBtnMark.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jideBtnMark.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jideBtnMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jideBtnMarkActionPerformed(evt);
            }
        });
        tbMenu.add(jideBtnMark);

        jideBtnPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/Dollar_32.png"))); // NOI18N
        jideBtnPayment.setToolTipText("Manager Payment");
        jideBtnPayment.setEnabled(false);
        jideBtnPayment.setFocusable(false);
        jideBtnPayment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jideBtnPayment.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jideBtnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jideBtnPaymentActionPerformed(evt);
            }
        });
        tbMenu.add(jideBtnPayment);

        jideBtnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/Statistic_bg.png"))); // NOI18N
        jideBtnReport.setToolTipText("Manager Report");
        jideBtnReport.setEnabled(false);
        jideBtnReport.setFocusable(false);
        jideBtnReport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jideBtnReport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jideBtnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jideBtnReportActionPerformed(evt);
            }
        });
        tbMenu.add(jideBtnReport);

        panelLogo.add(tbMenu, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(panelLogo, gridBagConstraints);

        panelLeft.setBackground(new java.awt.Color(255, 255, 255));
        panelLeft.setMinimumSize(new java.awt.Dimension(1024, 600));
        panelLeft.setPreferredSize(new java.awt.Dimension(1024, 600));
        panelLeft.setLayout(new java.awt.GridBagLayout());

        tpnBusiness.setBackground(new java.awt.Color(255, 255, 255));
        tpnBusiness.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tpnBusiness.setEnabled(false);
        tpnBusiness.setFont(new java.awt.Font("Tahoma", 1, 12));
        tpnBusiness.setMaximumSize(new java.awt.Dimension(1024, 600));
        tpnBusiness.setMinimumSize(new java.awt.Dimension(1024, 600));
        tpnBusiness.setPreferredSize(new java.awt.Dimension(1024, 600));

        pnlHome.setBackground(new java.awt.Color(255, 255, 255));
        pnlHome.setEnabled(false);
        pnlHome.setMaximumSize(new java.awt.Dimension(800, 600));
        pnlHome.setMinimumSize(new java.awt.Dimension(800, 600));
        pnlHome.setPreferredSize(new java.awt.Dimension(800, 600));
        pnlHome.setRequestFocusEnabled(false);
        pnlHome.setLayout(new java.awt.GridBagLayout());

        pnlHome = homeAdmin;

        tpnBusiness.addTab("Home                  ", new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/arrow.png")), pnlHome); // NOI18N

        pnlEmployee.setBackground(new java.awt.Color(255, 255, 255));
        pnlEmployee.setEnabled(false);

        pnlEmployee = emp;

        tpnBusiness.addTab("Employee            ", new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/arrow.png")), pnlEmployee); // NOI18N

        pnlStudent.setBackground(new java.awt.Color(255, 255, 255));
        pnlStudent.setEnabled(false);

        pnlStudent = student;

        tpnBusiness.addTab("Student", new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/arrow.png")), pnlStudent); // NOI18N

        pnlRegister.setBackground(new java.awt.Color(255, 255, 255));
        pnlRegister.setEnabled(false);
        pnlRegister = register;
        tpnBusiness.addTab("Register", new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/arrow.png")), pnlRegister); // NOI18N

        pnlCourse.setBackground(new java.awt.Color(255, 255, 255));
        pnlCourse.setEnabled(false);

        pnlCourse = course;

        tpnBusiness.addTab("Course", new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/arrow.png")), pnlCourse); // NOI18N

        pnlPayment.setBackground(new java.awt.Color(255, 255, 255));
        pnlPayment.setEnabled(false);
        pnlPayment = payment;
        tpnBusiness.addTab("Payment", new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/arrow.png")), pnlPayment); // NOI18N

        pnlSubject.setBackground(new java.awt.Color(255, 255, 255));
        pnlSubject.setEnabled(false);
        pnlSubject = subject;
        tpnBusiness.addTab("Subject", new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/arrow.png")), pnlSubject); // NOI18N

        pnlMark.setBackground(new java.awt.Color(255, 255, 255));
        pnlMark.setEnabled(false);
        pnlMark = mark;
        tpnBusiness.addTab("Mark", new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/arrow.png")), pnlMark); // NOI18N

        pnlCertificate.setBackground(new java.awt.Color(255, 255, 255));
        pnlCertificate.setEnabled(false);
        pnlCertificate = cer;
        tpnBusiness.addTab("Certificate", new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/arrow.png")), pnlCertificate); // NOI18N

        pnlAccount.setBackground(new java.awt.Color(255, 255, 255));
        pnlAccount.setEnabled(false);
        pnlAccount = account;
        tpnBusiness.addTab("Account             ", new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/arrow.png")), pnlAccount); // NOI18N

        pnlPermission.setBackground(new java.awt.Color(255, 255, 255));
        pnlPermission.setEnabled(false);
        pnlPermission.setMinimumSize(new java.awt.Dimension(860, 600));
        pnlPermission.setPreferredSize(new java.awt.Dimension(860, 600));
        pnlPermission = per;
        tpnBusiness.addTab("Permission", new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/arrow.png")), pnlPermission); // NOI18N

        pnlViewMark.setBackground(new java.awt.Color(255, 255, 255));
        pnlViewMark.setEnabled(false);

        javax.swing.GroupLayout pnlViewMarkLayout = new javax.swing.GroupLayout(pnlViewMark);
        pnlViewMark.setLayout(pnlViewMarkLayout);
        pnlViewMarkLayout.setHorizontalGroup(
            pnlViewMarkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        pnlViewMarkLayout.setVerticalGroup(
            pnlViewMarkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        pnlViewMark = viewMark;

        tpnBusiness.addTab("View Mark", new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/arrow.png")), pnlViewMark); // NOI18N

        pnlViewPayment.setBackground(new java.awt.Color(255, 255, 255));
        pnlViewPayment.setEnabled(false);

        javax.swing.GroupLayout pnlViewPaymentLayout = new javax.swing.GroupLayout(pnlViewPayment);
        pnlViewPayment.setLayout(pnlViewPaymentLayout);
        pnlViewPaymentLayout.setHorizontalGroup(
            pnlViewPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        pnlViewPaymentLayout.setVerticalGroup(
            pnlViewPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        pnlViewPayment = viewPayment;

        tpnBusiness.addTab("View Payment", new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/arrow.png")), pnlViewPayment); // NOI18N

        pnlDevelopDegree.setBackground(new java.awt.Color(255, 255, 255));
        pnlDevelopDegree.setEnabled(false);

        javax.swing.GroupLayout pnlDevelopDegreeLayout = new javax.swing.GroupLayout(pnlDevelopDegree);
        pnlDevelopDegree.setLayout(pnlDevelopDegreeLayout);
        pnlDevelopDegreeLayout.setHorizontalGroup(
            pnlDevelopDegreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        pnlDevelopDegreeLayout.setVerticalGroup(
            pnlDevelopDegreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        pnlDevelopDegree =  developDegree;

        tpnBusiness.addTab("Develop Degree", new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/arrow.png")), pnlDevelopDegree); // NOI18N

        pnlReport.setBackground(new java.awt.Color(255, 255, 255));
        pnlReport.setEnabled(false);

        javax.swing.GroupLayout pnlReportLayout = new javax.swing.GroupLayout(pnlReport);
        pnlReport.setLayout(pnlReportLayout);
        pnlReportLayout.setHorizontalGroup(
            pnlReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        pnlReportLayout.setVerticalGroup(
            pnlReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        tpnBusiness.addTab("Report", new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/arrow.png")), pnlReport); // NOI18N

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelLeft.add(tpnBusiness, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(panelLeft, gridBagConstraints);

        StatusPnl.setMinimumSize(new java.awt.Dimension(1024, 20));
        StatusPnl.setPreferredSize(new java.awt.Dimension(1024, 20));
        StatusPnl.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(StatusPnl, gridBagConstraints);

        mnuBSystem.setMaximumSize(new java.awt.Dimension(1024, 23));
        mnuBSystem.setMinimumSize(new java.awt.Dimension(1024, 23));
        mnuBSystem.setPreferredSize(new java.awt.Dimension(1024, 23));

        mnuSystem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/gear.png"))); // NOI18N
        mnuSystem.setText("System");

        mnuILoginSystem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        mnuILoginSystem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/IconLogin.png"))); // NOI18N
        mnuILoginSystem.setText("Login System");
        mnuILoginSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuILoginSystemActionPerformed(evt);
            }
        });
        mnuSystem.add(mnuILoginSystem);

        mnuILogoutSystem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        mnuILogoutSystem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/signout.png"))); // NOI18N
        mnuILogoutSystem.setText("Logout System");
        mnuILogoutSystem.setEnabled(false);
        mnuILogoutSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuILogoutSystemActionPerformed(evt);
            }
        });
        mnuSystem.add(mnuILogoutSystem);

        menuIChangePass.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menuIChangePass.setText("Change Password");
        menuIChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIChangePassActionPerformed(evt);
            }
        });
        mnuSystem.add(menuIChangePass);

        mnuIConfiguration.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        mnuIConfiguration.setText("Configuration DB");
        mnuIConfiguration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIConfigurationActionPerformed(evt);
            }
        });
        mnuSystem.add(mnuIConfiguration);

        mnuOptions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/gear.png"))); // NOI18N
        mnuOptions.setText("Options");
        mnuOptions.setEnabled(false);

        mnuSkin.setText("Skin");

        buttonGroupSkin.add(radioWindows);
        radioWindows.setSelected(true);
        radioWindows.setText("Windows");
        radioWindows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioWindowsActionPerformed(evt);
            }
        });
        mnuSkin.add(radioWindows);

        buttonGroupSkin.add(radioMetal);
        radioMetal.setText("Metal");
        radioMetal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMetalActionPerformed(evt);
            }
        });
        mnuSkin.add(radioMetal);

        buttonGroupSkin.add(radioNimbus);
        radioNimbus.setText("Nimbus");
        radioNimbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNimbusActionPerformed(evt);
            }
        });
        mnuSkin.add(radioNimbus);

        buttonGroupSkin.add(radioJgoodies);
        radioJgoodies.setText("Jgoodies");
        radioJgoodies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioJgoodiesActionPerformed(evt);
            }
        });
        mnuSkin.add(radioJgoodies);

        mnuOptions.add(mnuSkin);

        mnuTheme.setText("Theme");

        buttonGroupTheme.add(radioDarkStar);
        radioDarkStar.setSelected(true);
        radioDarkStar.setText("Dark Star");
        radioDarkStar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDarkStarActionPerformed(evt);
            }
        });
        mnuTheme.add(radioDarkStar);

        buttonGroupTheme.add(radioDesertBlue);
        radioDesertBlue.setText("Deser Blue");
        radioDesertBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDesertBlueActionPerformed(evt);
            }
        });
        mnuTheme.add(radioDesertBlue);

        buttonGroupTheme.add(radioDesertGreen);
        radioDesertGreen.setText("Deser Green");
        radioDesertGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDesertGreenActionPerformed(evt);
            }
        });
        mnuTheme.add(radioDesertGreen);

        buttonGroupTheme.add(radioDesertYellow);
        radioDesertYellow.setText("Deser Yellow");
        radioDesertYellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDesertYellowActionPerformed(evt);
            }
        });
        mnuTheme.add(radioDesertYellow);

        buttonGroupTheme.add(radioExperienceBlue);
        radioExperienceBlue.setText("Experience Blue");
        radioExperienceBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioExperienceBlueActionPerformed(evt);
            }
        });
        mnuTheme.add(radioExperienceBlue);

        buttonGroupTheme.add(radioExperienceGreen);
        radioExperienceGreen.setText("Experience Green");
        radioExperienceGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioExperienceGreenActionPerformed(evt);
            }
        });
        mnuTheme.add(radioExperienceGreen);

        buttonGroupTheme.add(radioExperenceRoyale);
        radioExperenceRoyale.setText("Experence Royale");
        radioExperenceRoyale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioExperenceRoyaleActionPerformed(evt);
            }
        });
        mnuTheme.add(radioExperenceRoyale);

        buttonGroupTheme.add(radioLightGray);
        radioLightGray.setText("Light Gray");
        radioLightGray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioLightGrayActionPerformed(evt);
            }
        });
        mnuTheme.add(radioLightGray);

        buttonGroupTheme.add(radioSilver);
        radioSilver.setText("Silver");
        radioSilver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSilverActionPerformed(evt);
            }
        });
        mnuTheme.add(radioSilver);

        buttonGroupTheme.add(radioSkyBlue);
        radioSkyBlue.setText("Sky Blue");
        radioSkyBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSkyBlueActionPerformed(evt);
            }
        });
        mnuTheme.add(radioSkyBlue);

        buttonGroupTheme.add(radioSkyBluer);
        radioSkyBluer.setText("Sky Bluer");
        radioSkyBluer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSkyBluerActionPerformed(evt);
            }
        });
        mnuTheme.add(radioSkyBluer);

        buttonGroupTheme.add(radioSkyGreen);
        radioSkyGreen.setText("Sky Green");
        radioSkyGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSkyGreenActionPerformed(evt);
            }
        });
        mnuTheme.add(radioSkyGreen);

        buttonGroupTheme.add(radioSkyPink);
        radioSkyPink.setText("Sky Pink");
        radioSkyPink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSkyPinkActionPerformed(evt);
            }
        });
        mnuTheme.add(radioSkyPink);

        buttonGroupTheme.add(radioSkyRed);
        radioSkyRed.setText("Sky Red");
        radioSkyRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSkyRedActionPerformed(evt);
            }
        });
        mnuTheme.add(radioSkyRed);

        buttonGroupTheme.add(radioSkyYellow);
        radioSkyYellow.setText("Sky Yellow");
        radioSkyYellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSkyYellowActionPerformed(evt);
            }
        });
        mnuTheme.add(radioSkyYellow);

        mnuOptions.add(mnuTheme);

        mnuSystem.add(mnuOptions);
        mnuSystem.add(jSeparator1);

        mnuIExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        mnuIExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/exit.png"))); // NOI18N
        mnuIExit.setText("Exit");
        mnuIExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIExitActionPerformed(evt);
            }
        });
        mnuSystem.add(mnuIExit);

        mnuBSystem.add(mnuSystem);

        mnuHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/help.png"))); // NOI18N
        mnuHelp.setText("Help");

        mnuIHelpContent.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mnuIHelpContent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/help (2).png"))); // NOI18N
        mnuIHelpContent.setText("Help Contents");
        mnuHelp.add(mnuIHelpContent);

        mnuIAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        mnuIAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/about.png"))); // NOI18N
        mnuIAbout.setText("About");
        mnuIAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIAboutActionPerformed(evt);
            }
        });
        mnuHelp.add(mnuIAbout);

        mnuBSystem.add(mnuHelp);

        setJMenuBar(mnuBSystem);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuILoginSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuILoginSystemActionPerformed
        // TODO add your handling code here:
        dlgLogin login = new dlgLogin(this, true);
        login.setVisible(true);
    }//GEN-LAST:event_mnuILoginSystemActionPerformed

    private void mnuIAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIAboutActionPerformed
        // TODO add your handling code here:
        dlgAbout about = new dlgAbout(this, true);
        about.setVisible(true);
    }//GEN-LAST:event_mnuIAboutActionPerformed

    private void radioWindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioWindowsActionPerformed
        // TODO add your handling code here:
        if (radioWindows.isSelected()) {
            lookandfeel = guip.PLAF_WINDOWS;
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioWindowsActionPerformed

    private void radioMetalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMetalActionPerformed
        // TODO add your handling code here:
        if (radioMetal.isSelected()) {
            lookandfeel = guip.PLAF_METAL;
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioMetalActionPerformed

    private void radioNimbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNimbusActionPerformed
        // TODO add your handling code here:
        if (radioNimbus.isSelected()) {
            lookandfeel = guip.PLAF_NIMBUS;
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioNimbusActionPerformed

    private void menuIChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIChangePassActionPerformed
        // TODO add your handling code here:
        if (accCur != null) {
            dlgChangePass changePass = new dlgChangePass(this, true, this.accCur);
            changePass.setVisible(true);
        }
    }//GEN-LAST:event_menuIChangePassActionPerformed

    private void mnuIManagmentEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIManagmentEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuIManagmentEmpActionPerformed

    private void mnuIHelpContentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIHelpContentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuIHelpContentActionPerformed

    private void mnuIExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuIExitActionPerformed

    private void mnuISwitchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuISwitchUserActionPerformed
        // TODO add your handling code here:
        if (this.accCur != null) {
            accCur = null;
            this.setVisible(false);
            dlgLogin login = new dlgLogin(this);
            login.setVisible(true);
        }
    }//GEN-LAST:event_mnuISwitchUserActionPerformed

    private void mnuILogoutSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuILogoutSystemActionPerformed
        // TODO add your handling code here:
        if (this.accCur != null) {
            accCur = null;
            this.isLogout();
            dlgLogin login = new dlgLogin(this, true);
            login.setVisible(true);
        }
    }//GEN-LAST:event_mnuILogoutSystemActionPerformed

    private void radioJgoodiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioJgoodiesActionPerformed
        // TODO add your handling code here:
        if (radioJgoodies.isSelected()) {
            lookandfeel = guip.PLAF_JGOODIES;
            guidao.setGUI(lookandfeel, theme);
        }
}//GEN-LAST:event_radioJgoodiesActionPerformed

    private void radioDarkStarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDarkStarActionPerformed
        // TODO add your handling code here:
        if (radioDarkStar.isSelected()) {
            theme = "DarkStar";
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioDarkStarActionPerformed

    private void radioDesertBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDesertBlueActionPerformed
        // TODO add your handling code here:
        if (radioDesertBlue.isSelected()) {
            theme = "DesertBlue";
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioDesertBlueActionPerformed

    private void radioDesertGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDesertGreenActionPerformed
        // TODO add your handling code here:
        if (radioDesertGreen.isSelected()) {
            theme = "DesertGreen";
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioDesertGreenActionPerformed

    private void radioDesertYellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDesertYellowActionPerformed
        // TODO add your handling code here:
        if (radioDesertYellow.isSelected()) {
            theme = "DesertYellow";
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioDesertYellowActionPerformed

    private void radioExperienceBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioExperienceBlueActionPerformed
        // TODO add your handling code here:
        if (radioExperienceBlue.isSelected()) {
            theme = "ExperienceBlue";
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioExperienceBlueActionPerformed

    private void radioExperienceGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioExperienceGreenActionPerformed
        // TODO add your handling code here:
        if (radioExperienceGreen.isSelected()) {
            theme = "ExperienceGreen";
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioExperienceGreenActionPerformed

    private void radioExperenceRoyaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioExperenceRoyaleActionPerformed
        // TODO add your handling code here:
        if (radioExperenceRoyale.isSelected()) {
            theme = "ExperienceRoyale";
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioExperenceRoyaleActionPerformed

    private void radioLightGrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioLightGrayActionPerformed
        // TODO add your handling code here:
        if (radioLightGray.isSelected()) {
            theme = "LightGray";
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioLightGrayActionPerformed

    private void radioSilverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSilverActionPerformed
        // TODO add your handling code here:
        if (radioSilver.isSelected()) {
            theme = "Silver";
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioSilverActionPerformed

    private void radioSkyBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSkyBlueActionPerformed
        // TODO add your handling code here:
        if (radioSkyBlue.isSelected()) {
            theme = "SkyBlue";
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioSkyBlueActionPerformed

    private void radioSkyBluerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSkyBluerActionPerformed
        // TODO add your handling code here:
        if (radioSkyBluer.isSelected()) {
            theme = "SkyBluer";
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioSkyBluerActionPerformed

    private void radioSkyGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSkyGreenActionPerformed
        // TODO add your handling code here:
        if (radioSkyGreen.isSelected()) {
            theme = "SkyGreen";
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioSkyGreenActionPerformed

    private void radioSkyPinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSkyPinkActionPerformed
        // TODO add your handling code here:
        if (radioSkyPink.isSelected()) {
            theme = "SkyPink";
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioSkyPinkActionPerformed

    private void radioSkyRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSkyRedActionPerformed
        // TODO add your handling code here:
        if (radioSkyRed.isSelected()) {
            theme = "SkyRed";
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioSkyRedActionPerformed

    private void radioSkyYellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSkyYellowActionPerformed
        // TODO add your handling code here:
        if (radioSkyYellow.isSelected()) {
            theme = "SkyYellow";
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioSkyYellowActionPerformed

    private void jideBtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jideBtnHomeActionPerformed
        // TODO add your handling code here:
        tpnBusiness.setSelectedComponent(pnlHome);
    }//GEN-LAST:event_jideBtnHomeActionPerformed

    private void jideBtnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jideBtnEmployeeActionPerformed
        // TODO add your handling code here:
        tpnBusiness.setSelectedComponent(pnlEmployee);
    }//GEN-LAST:event_jideBtnEmployeeActionPerformed

    private void jideBtnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jideBtnStudentActionPerformed
        // TODO add your handling code here:
        tpnBusiness.setSelectedComponent(pnlStudent);
    }//GEN-LAST:event_jideBtnStudentActionPerformed

    private void jideBtnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jideBtnRegisterActionPerformed
        // TODO add your handling code here:
        tpnBusiness.setSelectedComponent(pnlRegister);
    }//GEN-LAST:event_jideBtnRegisterActionPerformed

    private void jideBtnCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jideBtnCourseActionPerformed
        // TODO add your handling code here:
        tpnBusiness.setSelectedComponent(pnlCourse);
    }//GEN-LAST:event_jideBtnCourseActionPerformed

    private void jideBtnSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jideBtnSubjectActionPerformed
        // TODO add your handling code here:
        tpnBusiness.setSelectedComponent(pnlSubject);
    }//GEN-LAST:event_jideBtnSubjectActionPerformed

    private void jideBtnCertificateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jideBtnCertificateActionPerformed
        // TODO add your handling code here:
        tpnBusiness.setSelectedComponent(pnlCertificate);
    }//GEN-LAST:event_jideBtnCertificateActionPerformed

    private void jideBtnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jideBtnAccountActionPerformed
        // TODO add your handling code here:
        tpnBusiness.setSelectedComponent(pnlAccount);
    }//GEN-LAST:event_jideBtnAccountActionPerformed

    private void jideBtnMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jideBtnMarkActionPerformed
        // TODO add your handling code here:
        tpnBusiness.setSelectedComponent(pnlMark);
    }//GEN-LAST:event_jideBtnMarkActionPerformed

    private void jideBtnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jideBtnPaymentActionPerformed
        // TODO add your handling code here:
        tpnBusiness.setSelectedComponent(pnlPayment);
    }//GEN-LAST:event_jideBtnPaymentActionPerformed

    private void jideBtnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jideBtnReportActionPerformed
        // TODO add your handling code here:
        tpnBusiness.setSelectedComponent(pnlReport);

    }//GEN-LAST:event_jideBtnReportActionPerformed

    private void mnuIConfigurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIConfigurationActionPerformed
        // TODO add your handling code here:
        dlgConfigurationDB configurationDB = new dlgConfigurationDB(this, true);
        configurationDB.setVisible(true);
    }//GEN-LAST:event_mnuIConfigurationActionPerformed

    public void isLogout() {
//        pnlHome.removeAll();
//        pnlHome.add(homeAdmin);
//
//        pnlEmployee.removeAll();
//        pnlEmployee.add(emp);
//
//        pnlStudent.removeAll();
//        pnlStudent.add(student);
//
//        pnlRegister.removeAll();
//        pnlRegister.add(register);
//
//        pnlCourse.removeAll();
//        pnlCourse.add(course);
//
//        pnlPayment.removeAll();
//        pnlPayment.add(payment);
//
//        pnlSubject.removeAll();
//        pnlSubject.add(subject);
//
//        pnlMark.removeAll();
//        pnlMark.add(mark);
//
//        pnlCertificate.removeAll();
//        pnlCertificate.add(cer);
//
//        pnlAccount.removeAll();
//        pnlAccount.add(account);
//
//        pnlPermission.removeAll();
//        pnlPermission.add(per);
//
//        pnlViewMark.removeAll();
//        pnlViewMark.add(viewMark);
//
//        pnlViewPayment.removeAll();
//        pnlViewPayment.add(viewPayment);
//
//        pnlDevelopDegree.removeAll();
//        pnlDevelopDegree.add(developDegree);
//        pnlReport.add(report);

        tpnBusiness.setEnabled(false);
        jideBtnHome.setEnabled(false);
        jideBtnEmployee.setEnabled(false);
        jideBtnStudent.setEnabled(false);
        jideBtnCourse.setEnabled(false);
        jideBtnSubject.setEnabled(false);
        jideBtnAccount.setEnabled(false);
        jideBtnCertificate.setEnabled(false);
        jideBtnAccount.setEnabled(false);
        jideBtnMark.setEnabled(false);
        jideBtnReport.setEnabled(false);
        jideBtnPayment.setEnabled(false);
        jideBtnRegister.setEnabled(false);

        mnuILogoutSystem.setVisible(false);
        tpnBusiness.setEnabled(false);
        menuIChangePass.setEnabled(false);
        mnuOptions.setEnabled(false);
        mnuILoginSystem.setVisible(true);
    }

    public void isLogin() {
        tpnBusiness.setSelectedComponent(pnlHome);
        jideBtnHome.setEnabled(true);
        jideBtnEmployee.setEnabled(true);
        jideBtnStudent.setEnabled(true);
        jideBtnCourse.setEnabled(true);
        jideBtnSubject.setEnabled(true);
        jideBtnAccount.setEnabled(true);
        jideBtnCertificate.setEnabled(true);
        jideBtnAccount.setEnabled(true);
        jideBtnMark.setEnabled(true);
        jideBtnReport.setEnabled(true);
        jideBtnPayment.setEnabled(true);
        jideBtnRegister.setEnabled(true);

        if (this.accCur != null) {
            mnuILogoutSystem.setVisible(true);
            mnuILogoutSystem.setEnabled(true);
            tpnBusiness.setEnabled(true);
            menuIChangePass.setEnabled(true);
            mnuOptions.setEnabled(true);
            mnuILoginSystem.setVisible(false);

            if (perDao.readByName("Admin").getId() == this.accCur.getPermission()) {
            } else if (perDao.readByName("Employee").getId() == this.accCur.getPermission()) {

                tpnBusiness.remove(pnlEmployee);
                tpnBusiness.remove(pnlStudent);
                tpnBusiness.remove(pnlRegister);
                tpnBusiness.remove(pnlCourse);
                tpnBusiness.remove(pnlSubject);
                tpnBusiness.remove(pnlPayment);
                tpnBusiness.remove(pnlMark);
                tpnBusiness.remove(pnlCertificate);
                tpnBusiness.remove(pnlPermission);
                tpnBusiness.remove(pnlAccount);
                pnlHome.removeAll();
                pnlHome.add(new pnlHomeEmp(this));

                jideBtnEmployee.setVisible(false);
                jideBtnStudent.setVisible(false);
                jideBtnCourse.setVisible(false);
                jideBtnSubject.setVisible(false);
                jideBtnAccount.setVisible(false);
                jideBtnCertificate.setVisible(false);
                jideBtnAccount.setVisible(false);
                jideBtnMark.setVisible(false);
                jideBtnRegister.setVisible(false);
                jideBtnPayment.setVisible(false);

            } else {
                tpnBusiness.remove(pnlEmployee);
                tpnBusiness.remove(pnlStudent);
                tpnBusiness.remove(pnlRegister);
                tpnBusiness.remove(pnlCourse);
                tpnBusiness.remove(pnlSubject);
                tpnBusiness.remove(pnlPayment);
                tpnBusiness.remove(pnlMark);
                tpnBusiness.remove(pnlCertificate);
                tpnBusiness.remove(pnlPermission);
                tpnBusiness.remove(pnlDevelopDegree);
                tpnBusiness.remove(pnlAccount);
                pnlHome.removeAll();
                pnlHome.add(new pnlHomeStudent(this));


                jideBtnEmployee.setVisible(false);
                jideBtnStudent.setVisible(false);
                jideBtnCourse.setVisible(false);
                jideBtnSubject.setVisible(false);
                jideBtnAccount.setVisible(false);
                jideBtnCertificate.setVisible(false);
                jideBtnAccount.setVisible(false);
                jideBtnMark.setVisible(false);
                jideBtnPayment.setVisible(false);
                jideBtnRegister.setVisible(false);
            }
        } else {
            mnuILogoutSystem.setVisible(false);
            tpnBusiness.setEnabled(false);
            menuIChangePass.setEnabled(false);
            mnuOptions.setEnabled(false);
            mnuILoginSystem.setVisible(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmMain().setVisible(true);


            }
        });


    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel StatusPnl;
    private javax.swing.ButtonGroup buttonGroupSkin;
    private javax.swing.ButtonGroup buttonGroupTheme;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private com.jidesoft.swing.JideButton jideBtnAccount;
    private com.jidesoft.swing.JideButton jideBtnCertificate;
    private com.jidesoft.swing.JideButton jideBtnCourse;
    private com.jidesoft.swing.JideButton jideBtnEmployee;
    private com.jidesoft.swing.JideButton jideBtnHome;
    private com.jidesoft.swing.JideButton jideBtnMark;
    private com.jidesoft.swing.JideButton jideBtnPayment;
    private com.jidesoft.swing.JideButton jideBtnRegister;
    private com.jidesoft.swing.JideButton jideBtnReport;
    private com.jidesoft.swing.JideButton jideBtnStudent;
    private com.jidesoft.swing.JideButton jideBtnSubject;
    private javax.swing.JMenuItem menuIChangePass;
    private javax.swing.JMenuBar mnuBSystem;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenuItem mnuIAbout;
    private javax.swing.JMenuItem mnuIConfiguration;
    private javax.swing.JMenuItem mnuIExit;
    private javax.swing.JMenuItem mnuIHelpContent;
    private javax.swing.JMenuItem mnuILoginSystem;
    private javax.swing.JMenuItem mnuILogoutSystem;
    private javax.swing.JMenu mnuOptions;
    private javax.swing.JMenu mnuSkin;
    private javax.swing.JMenu mnuSystem;
    private javax.swing.JMenu mnuTheme;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JPanel panelLogo;
    private javax.swing.JPanel pnlAccount;
    private javax.swing.JPanel pnlCertificate;
    private javax.swing.JPanel pnlCourse;
    private javax.swing.JPanel pnlDevelopDegree;
    private javax.swing.JPanel pnlEmployee;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlMark;
    private javax.swing.JPanel pnlPayment;
    private javax.swing.JPanel pnlPermission;
    private javax.swing.JPanel pnlRegister;
    public javax.swing.JPanel pnlReport;
    private javax.swing.JPanel pnlStudent;
    private javax.swing.JPanel pnlSubject;
    private javax.swing.JPanel pnlViewMark;
    private javax.swing.JPanel pnlViewPayment;
    private javax.swing.JRadioButtonMenuItem radioDarkStar;
    private javax.swing.JRadioButtonMenuItem radioDesertBlue;
    private javax.swing.JRadioButtonMenuItem radioDesertGreen;
    private javax.swing.JRadioButtonMenuItem radioDesertYellow;
    private javax.swing.JRadioButtonMenuItem radioExperenceRoyale;
    private javax.swing.JRadioButtonMenuItem radioExperienceBlue;
    private javax.swing.JRadioButtonMenuItem radioExperienceGreen;
    private javax.swing.JRadioButtonMenuItem radioJgoodies;
    private javax.swing.JRadioButtonMenuItem radioLightGray;
    private javax.swing.JRadioButtonMenuItem radioMetal;
    private javax.swing.JRadioButtonMenuItem radioNimbus;
    private javax.swing.JRadioButtonMenuItem radioSilver;
    private javax.swing.JRadioButtonMenuItem radioSkyBlue;
    private javax.swing.JRadioButtonMenuItem radioSkyBluer;
    private javax.swing.JRadioButtonMenuItem radioSkyGreen;
    private javax.swing.JRadioButtonMenuItem radioSkyPink;
    private javax.swing.JRadioButtonMenuItem radioSkyRed;
    private javax.swing.JRadioButtonMenuItem radioSkyYellow;
    private javax.swing.JRadioButtonMenuItem radioWindows;
    private javax.swing.JToolBar tbMenu;
    public javax.swing.JTabbedPane tpnBusiness;
    // End of variables declaration//GEN-END:variables
}
