/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * dlgChooseReport.java
 *
 * Created on Apr 2, 2011, 9:35:36 AM
 */
package com.hueic.CerGS.ui;

import com.hueic.CerGS.ui.report.pnlCertificateDevelopedReport;
import com.hueic.CerGS.ui.report.pnlCertificateReport;
import com.hueic.CerGS.ui.report.pnlEmployeeReport;
import com.hueic.CerGS.ui.report.pnlStudentFeeReport;
import com.hueic.CerGS.ui.report.pnlStudentMarkReport;
import com.hueic.CerGS.ui.report.pnlStudentNewRegistrationReport;
import com.hueic.CerGS.ui.report.pnlStudentReport;
import com.hueic.CerGS.ui.report.pnlSubjectInCourseReport;
import javax.swing.JPanel;

/**
 *
 * @author nhchung
 */
public class dlgChooseReport extends javax.swing.JPanel {

    private int type;
    pnlCertificateReport cerReport;
    pnlCertificateDevelopedReport cerDevReport;
    pnlEmployeeReport empReport;
    pnlStudentFeeReport feeReport;
    pnlStudentMarkReport markReport;
    pnlStudentNewRegistrationReport newRegistratorReport;
    pnlStudentReport studentReport;
    pnlSubjectInCourseReport subInCourseRerport;
    String courseId;
    String studentId;
    String subjectId;

    /** Creates new form dlgChooseReport */
    public dlgChooseReport(int type) {
        initComponents();
        this.type = type;
        cerReport = new pnlCertificateReport();
        cerDevReport = new pnlCertificateDevelopedReport();
        empReport = new pnlEmployeeReport();
        feeReport = new pnlStudentFeeReport(courseId);
        markReport = new pnlStudentMarkReport(studentId);
        newRegistratorReport = new pnlStudentNewRegistrationReport(courseId);
        studentReport = new pnlStudentReport(courseId);
        subInCourseRerport = new pnlSubjectInCourseReport(subjectId);

        switch (type) {
            case 0:
                this.pnlBrowser = cerReport;
                break;
            case 1:
                this.pnlBrowser = cerDevReport;
                break;
            case 2:
                this.pnlBrowser = empReport;
                break;
            case 3:
                this.pnlBrowser = feeReport;
                break;
            case 4:
                this.pnlBrowser = markReport;
                break;
            case 5:
                this.pnlBrowser = newRegistratorReport;
                break;
            case 6:
                this.pnlBrowser = studentReport;
                break;
            case 7:
                this.pnlBrowser = subInCourseRerport;
                break;
        }
    }

    public JPanel getViewer() {
        return this.pnlBrowser;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlButton = new javax.swing.JPanel();
        btnSelect = new javax.swing.JButton();
        pnlBrowser = new javax.swing.JPanel();

        pnlButton.setLayout(new javax.swing.BoxLayout(pnlButton, javax.swing.BoxLayout.LINE_AXIS));

        btnSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/arrow_left_green.png"))); // NOI18N
        btnSelect.setText("Back");
        btnSelect.setMargin(new java.awt.Insets(2, 5, 2, 5));
        btnSelect.setMaximumSize(new java.awt.Dimension(80, 25));
        btnSelect.setMinimumSize(new java.awt.Dimension(80, 25));
        btnSelect.setPreferredSize(new java.awt.Dimension(80, 25));
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });
        pnlButton.add(btnSelect);

        javax.swing.GroupLayout pnlBrowserLayout = new javax.swing.GroupLayout(pnlBrowser);
        pnlBrowser.setLayout(pnlBrowserLayout);
        pnlBrowserLayout.setHorizontalGroup(
            pnlBrowserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pnlBrowserLayout.setVerticalGroup(
            pnlBrowserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        pnlBrowser = pnlBrowser;

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlBrowser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pnlButton, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 5, Short.MAX_VALUE)
                    .addComponent(pnlBrowser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 5, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
}//GEN-LAST:event_btnSelectActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelect;
    protected javax.swing.JPanel pnlBrowser;
    protected javax.swing.JPanel pnlButton;
    // End of variables declaration//GEN-END:variables
}
