/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrm.java
 *
 * Created on Mar 13, 2011, 5:37:51 PM
 */
package com.hueic.CerGS.ui.main;

import com.hueic.CerGS.entity.Account;
import com.hueic.CerGS.ui.pnlAccount;
import com.hueic.CerGS.component.GUIProperties;
import com.hueic.CerGS.component.IconSystem;
import com.hueic.CerGS.dao.GUIDAO;
import com.hueic.CerGS.dao.PersonDAO;
import com.hueic.CerGS.entity.Person;
import com.hueic.CerGS.ui.dlgAbount;
import com.hueic.CerGS.ui.dlgChangePass;
import com.hueic.CerGS.ui.dlgLogin;
import com.hueic.CerGS.ui.pnlCertificate;
import com.hueic.CerGS.ui.pnlCourse;
import com.hueic.CerGS.ui.main.employee.frmEmployee;
import com.hueic.CerGS.ui.main.employee.frmViewInfo;
import com.hueic.CerGS.ui.pnlMark;
import com.hueic.CerGS.ui.pnlPayment;
import com.hueic.CerGS.ui.pnlPermission;
import com.hueic.CerGS.ui.pnlRegister;
import com.hueic.CerGS.ui.pnlSubject;
import java.net.URL;
import javax.help.CSH;
import javax.help.HelpBroker;
import javax.help.HelpSet;

/**
 *
 * @author nhchung
 */
public class frmMain extends javax.swing.JFrame {

    /** Creates new form MainFrm */
    GUIDAO guidao = null;
    GUIProperties guip = new GUIProperties();
    public Account accCur;
    String theme = "Silver";
    String lookandfeel = guip.PLAF_JGOODIES;
    pnlAccount account = new pnlAccount();
    pnlCertificate cer = new pnlCertificate();
    pnlCourse course = new pnlCourse();
    pnlMark mark = new pnlMark();
    pnlPayment payment = new pnlPayment();
    pnlRegister register = new pnlRegister();
    pnlPermission per = new pnlPermission();
    pnlSubject subject = new pnlSubject();
    
    public frmMain() {
        initComponents();
        setLocationRelativeTo(null);
        guidao = new GUIDAO(this);
        guidao.setGUI(lookandfeel, theme);
        bindingLang();
        new IconSystem(this);
        HelpSet hs = getHelpSet("com/hueic/CerGS/myhelp/sample.hs");
        HelpBroker hb = hs.createHelpBroker();

        // 2. assign help to components
        CSH.setHelpIDString(mnuIHelpContent, "top");
        mnuIHelpContent.addActionListener(new CSH.DisplayHelpFromSource(hb));
    }

    public HelpSet getHelpSet(String helpsetfile) {
        HelpSet hs = null;
        ClassLoader cl = this.getClass().getClassLoader();
        try {
            URL hsURL = HelpSet.findHelpSet(cl, helpsetfile);
            hs = new HelpSet(null, hsURL);
        } catch (Exception ee) {
            System.out.println("HelpSet: " + ee.getMessage());
            System.out.println("HelpSet: " + helpsetfile + " not found");
        }
        return hs;
    }

    public void bindingLang() {
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroupSkin = new javax.swing.ButtonGroup();
        buttonGroupTheme = new javax.swing.ButtonGroup();
        panelLogo = new javax.swing.JPanel();
        tbMenu = new javax.swing.JToolBar();
        jideButton1 = new com.jidesoft.swing.JideButton();
        jideButton2 = new com.jidesoft.swing.JideButton();
        panelLeft = new javax.swing.JPanel();
        tpnBusiness = new javax.swing.JTabbedPane();
        pnlHome = new javax.swing.JPanel();
        panelRight = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlAccount = new javax.swing.JPanel();
        pnlCertificate = new javax.swing.JPanel();
        pnlCourse = new javax.swing.JPanel();
        pnlMark = new javax.swing.JPanel();
        pnlPayment = new javax.swing.JPanel();
        pnlRegister = new javax.swing.JPanel();
        pnlPermission = new javax.swing.JPanel();
        pnlSubject = new javax.swing.JPanel();
        StatusPnl = new javax.swing.JPanel();
        mnuBSystem = new javax.swing.JMenuBar();
        mnuSystem = new javax.swing.JMenu();
        mnuISwitchUser = new javax.swing.JMenuItem();
        mnuILoginSystem = new javax.swing.JMenuItem();
        mnuILogoutSystem = new javax.swing.JMenuItem();
        menuIChangePass = new javax.swing.JMenuItem();
        mnuOptions = new javax.swing.JMenu();
        mnuSkin = new javax.swing.JMenu();
        radioWindows = new javax.swing.JRadioButtonMenuItem();
        radioMetal = new javax.swing.JRadioButtonMenuItem();
        radioNimbus = new javax.swing.JRadioButtonMenuItem();
        radioJgoodies = new javax.swing.JRadioButtonMenuItem();
        mnuTheme = new javax.swing.JMenu();
        radioDarkStar = new javax.swing.JRadioButtonMenuItem();
        radioDesertBlue = new javax.swing.JRadioButtonMenuItem();
        radioDesertGreen = new javax.swing.JRadioButtonMenuItem();
        radioDesertYellow = new javax.swing.JRadioButtonMenuItem();
        radioExperienceBlue = new javax.swing.JRadioButtonMenuItem();
        radioExperienceGreen = new javax.swing.JRadioButtonMenuItem();
        radioExperenceRoyale = new javax.swing.JRadioButtonMenuItem();
        radioLightGray = new javax.swing.JRadioButtonMenuItem();
        radioSilver = new javax.swing.JRadioButtonMenuItem();
        radioSkyBlue = new javax.swing.JRadioButtonMenuItem();
        radioSkyBluer = new javax.swing.JRadioButtonMenuItem();
        radioSkyGreen = new javax.swing.JRadioButtonMenuItem();
        radioSkyPink = new javax.swing.JRadioButtonMenuItem();
        radioSkyRed = new javax.swing.JRadioButtonMenuItem();
        radioSkyYellow = new javax.swing.JRadioButtonMenuItem();
        mnuIViewInformation = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuIExit = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mnuIHelpContent = new javax.swing.JMenuItem();
        mnuIAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Certificate Generation System");
        setMinimumSize(new java.awt.Dimension(1024, 720));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panelLogo.setMinimumSize(new java.awt.Dimension(1024, 40));
        panelLogo.setPreferredSize(new java.awt.Dimension(1024, 40));
        panelLogo.setLayout(new java.awt.GridBagLayout());

        tbMenu.setRollover(true);
        tbMenu.setMaximumSize(new java.awt.Dimension(1024, 40));
        tbMenu.setMinimumSize(new java.awt.Dimension(1024, 40));
        tbMenu.setPreferredSize(new java.awt.Dimension(1024, 40));

        jideButton1.setFocusable(false);
        jideButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jideButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbMenu.add(jideButton1);

        jideButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/Statistic_bg.png"))); // NOI18N
        jideButton2.setFocusable(false);
        jideButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jideButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbMenu.add(jideButton2);

        panelLogo.add(tbMenu, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(panelLogo, gridBagConstraints);

        panelLeft.setBackground(new java.awt.Color(255, 255, 255));
        panelLeft.setMinimumSize(new java.awt.Dimension(1024, 600));
        panelLeft.setPreferredSize(new java.awt.Dimension(1024, 600));
        panelLeft.setLayout(new java.awt.GridBagLayout());

        tpnBusiness.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tpnBusiness.setFont(new java.awt.Font("Tahoma", 1, 12));
        tpnBusiness.setMinimumSize(new java.awt.Dimension(1024, 600));
        tpnBusiness.setPreferredSize(new java.awt.Dimension(1024, 600));

        pnlHome.setMaximumSize(new java.awt.Dimension(800, 600));
        pnlHome.setMinimumSize(new java.awt.Dimension(800, 600));
        pnlHome.setPreferredSize(new java.awt.Dimension(800, 600));
        pnlHome.setRequestFocusEnabled(false);

        panelRight.setBackground(new java.awt.Color(255, 255, 255));
        panelRight.setMaximumSize(new java.awt.Dimension(800, 600));
        panelRight.setMinimumSize(new java.awt.Dimension(800, 600));
        panelRight.setPreferredSize(new java.awt.Dimension(800, 600));
        panelRight.setLayout(new java.awt.GridBagLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/Dollar.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 20, 10);
        panelRight.add(jLabel2, gridBagConstraints);

        jLabel3.setForeground(new java.awt.Color(3, 3, 3));
        jLabel3.setText("Add new employee");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelRight.add(jLabel3, gridBagConstraints);

        jLabel4.setForeground(new java.awt.Color(3, 3, 3));
        jLabel4.setText("Search");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelRight.add(jLabel4, gridBagConstraints);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/Dollar.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 20, 10);
        panelRight.add(jLabel5, gridBagConstraints);

        jLabel6.setForeground(new java.awt.Color(3, 3, 3));
        jLabel6.setText("View");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 52;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelRight.add(jLabel6, gridBagConstraints);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/Dollar.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 20, 10);
        panelRight.add(jLabel7, gridBagConstraints);

        jLabel8.setForeground(new java.awt.Color(3, 3, 3));
        jLabel8.setText("Exit");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 52;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelRight.add(jLabel8, gridBagConstraints);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/Dollar.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 20, 10);
        panelRight.add(jLabel9, gridBagConstraints);

        jLabel10.setForeground(new java.awt.Color(3, 3, 3));
        jLabel10.setText("Logout");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelRight.add(jLabel10, gridBagConstraints);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/Dollar.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 20, 10);
        panelRight.add(jLabel11, gridBagConstraints);

        jLabel12.setForeground(new java.awt.Color(3, 3, 3));
        jLabel12.setText("Add new student");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelRight.add(jLabel12, gridBagConstraints);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/Dollar.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 20, 10);
        panelRight.add(jLabel13, gridBagConstraints);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel15.setForeground(new java.awt.Color(0, 0, 102));
        jLabel15.setText("<html>\n<body>\nCertificate Generator System\n</body>\n</html>");
        jLabel15.setMinimumSize(new java.awt.Dimension(261, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        panelRight.add(jLabel15, gridBagConstraints);

        jLabel16.setForeground(new java.awt.Color(3, 3, 3));
        jLabel16.setText("<html>\n<body>\nThis is a Certificate Department which works for “ABC” institute for developing  the certificate for the<br/> students who had completed their course. This system also deals with the student  registration,<br/> checking the payment scenario, inputting the marks of the students and after all verification is<br/>  done they develop the certificate of completion of the course for the students.\n</body>\n</html>\n");
        jLabel16.setMinimumSize(new java.awt.Dimension(600, 65));
        jLabel16.setPreferredSize(new java.awt.Dimension(600, 65));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 0);
        panelRight.add(jLabel16, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/logoFinal.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(40, 10, 0, 10);
        panelRight.add(jLabel1, gridBagConstraints);

        pnlHome.add(panelRight);

        tpnBusiness.addTab("  HOME                      ", new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/Charge.png")), pnlHome); // NOI18N

        pnlAccount = account;
        tpnBusiness.addTab("Account", pnlAccount);

        pnlCertificate = cer;
        tpnBusiness.addTab("Certificate", pnlCertificate);

        pnlCourse = course;
        tpnBusiness.addTab("Course", pnlCourse);

        pnlMark = mark;
        tpnBusiness.addTab("Mark", pnlMark);

        pnlPayment = payment;
        tpnBusiness.addTab("Payment", pnlPayment);

        pnlRegister = register;
        tpnBusiness.addTab("Register", pnlRegister);

        pnlPermission = per;
        tpnBusiness.addTab("Permission", pnlPermission);

        pnlSubject = subject;
        tpnBusiness.addTab("Subject", pnlSubject);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelLeft.add(tpnBusiness, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(panelLeft, gridBagConstraints);

        StatusPnl.setMinimumSize(new java.awt.Dimension(1024, 20));
        StatusPnl.setPreferredSize(new java.awt.Dimension(1024, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(StatusPnl, gridBagConstraints);

        mnuBSystem.setMaximumSize(new java.awt.Dimension(1024, 23));
        mnuBSystem.setMinimumSize(new java.awt.Dimension(1024, 23));
        mnuBSystem.setPreferredSize(new java.awt.Dimension(1024, 23));

        mnuSystem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/gear.png"))); // NOI18N
        mnuSystem.setText("System");

        mnuISwitchUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        mnuISwitchUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/switch.jpg"))); // NOI18N
        mnuISwitchUser.setText("Switch User");
        mnuISwitchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuISwitchUserActionPerformed(evt);
            }
        });
        mnuSystem.add(mnuISwitchUser);

        mnuILoginSystem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        mnuILoginSystem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/IconLogin.png"))); // NOI18N
        mnuILoginSystem.setText("Login System");
        mnuILoginSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuILoginSystemActionPerformed(evt);
            }
        });
        mnuSystem.add(mnuILoginSystem);

        mnuILogoutSystem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        mnuILogoutSystem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/signout.png"))); // NOI18N
        mnuILogoutSystem.setText("Logout System");
        mnuILogoutSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuILogoutSystemActionPerformed(evt);
            }
        });
        mnuSystem.add(mnuILogoutSystem);

        menuIChangePass.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menuIChangePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/iconchangepassword.png"))); // NOI18N
        menuIChangePass.setText("Change Password");
        menuIChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIChangePassActionPerformed(evt);
            }
        });
        mnuSystem.add(menuIChangePass);

        mnuOptions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/gear.png"))); // NOI18N
        mnuOptions.setText("Options");

        mnuSkin.setText("Skin");

        buttonGroupSkin.add(radioWindows);
        radioWindows.setSelected(true);
        radioWindows.setText("Windows");
        radioWindows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioWindowsActionPerformed(evt);
            }
        });
        mnuSkin.add(radioWindows);

        buttonGroupSkin.add(radioMetal);
        radioMetal.setText("Metal");
        radioMetal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMetalActionPerformed(evt);
            }
        });
        mnuSkin.add(radioMetal);

        buttonGroupSkin.add(radioNimbus);
        radioNimbus.setText("Nimbus");
        radioNimbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNimbusActionPerformed(evt);
            }
        });
        mnuSkin.add(radioNimbus);

        buttonGroupSkin.add(radioJgoodies);
        radioJgoodies.setText("Jgoodies");
        radioJgoodies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioJgoodiesActionPerformed(evt);
            }
        });
        mnuSkin.add(radioJgoodies);

        mnuOptions.add(mnuSkin);

        mnuTheme.setText("Theme");

        buttonGroupTheme.add(radioDarkStar);
        radioDarkStar.setSelected(true);
        radioDarkStar.setText("Dark Star");
        radioDarkStar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDarkStarActionPerformed(evt);
            }
        });
        mnuTheme.add(radioDarkStar);

        buttonGroupTheme.add(radioDesertBlue);
        radioDesertBlue.setText("Deser Blue");
        radioDesertBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDesertBlueActionPerformed(evt);
            }
        });
        mnuTheme.add(radioDesertBlue);

        buttonGroupTheme.add(radioDesertGreen);
        radioDesertGreen.setText("Deser Green");
        radioDesertGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDesertGreenActionPerformed(evt);
            }
        });
        mnuTheme.add(radioDesertGreen);

        buttonGroupTheme.add(radioDesertYellow);
        radioDesertYellow.setText("Deser Yellow");
        radioDesertYellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDesertYellowActionPerformed(evt);
            }
        });
        mnuTheme.add(radioDesertYellow);

        buttonGroupTheme.add(radioExperienceBlue);
        radioExperienceBlue.setText("Experience Blue");
        radioExperienceBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioExperienceBlueActionPerformed(evt);
            }
        });
        mnuTheme.add(radioExperienceBlue);

        buttonGroupTheme.add(radioExperienceGreen);
        radioExperienceGreen.setText("Experience Green");
        radioExperienceGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioExperienceGreenActionPerformed(evt);
            }
        });
        mnuTheme.add(radioExperienceGreen);

        buttonGroupTheme.add(radioExperenceRoyale);
        radioExperenceRoyale.setText("Experence Royale");
        radioExperenceRoyale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioExperenceRoyaleActionPerformed(evt);
            }
        });
        mnuTheme.add(radioExperenceRoyale);

        buttonGroupTheme.add(radioLightGray);
        radioLightGray.setText("Light Gray");
        radioLightGray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioLightGrayActionPerformed(evt);
            }
        });
        mnuTheme.add(radioLightGray);

        buttonGroupTheme.add(radioSilver);
        radioSilver.setText("Silver");
        radioSilver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSilverActionPerformed(evt);
            }
        });
        mnuTheme.add(radioSilver);

        buttonGroupTheme.add(radioSkyBlue);
        radioSkyBlue.setText("Sky Blue");
        radioSkyBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSkyBlueActionPerformed(evt);
            }
        });
        mnuTheme.add(radioSkyBlue);

        buttonGroupTheme.add(radioSkyBluer);
        radioSkyBluer.setText("Sky Bluer");
        radioSkyBluer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSkyBluerActionPerformed(evt);
            }
        });
        mnuTheme.add(radioSkyBluer);

        buttonGroupTheme.add(radioSkyGreen);
        radioSkyGreen.setText("Sky Green");
        radioSkyGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSkyGreenActionPerformed(evt);
            }
        });
        mnuTheme.add(radioSkyGreen);

        buttonGroupTheme.add(radioSkyPink);
        radioSkyPink.setText("Sky Pink");
        radioSkyPink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSkyPinkActionPerformed(evt);
            }
        });
        mnuTheme.add(radioSkyPink);

        buttonGroupTheme.add(radioSkyRed);
        radioSkyRed.setText("Sky Red");
        radioSkyRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSkyRedActionPerformed(evt);
            }
        });
        mnuTheme.add(radioSkyRed);

        buttonGroupTheme.add(radioSkyYellow);
        radioSkyYellow.setText("Sky Yellow");
        radioSkyYellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSkyYellowActionPerformed(evt);
            }
        });
        mnuTheme.add(radioSkyYellow);

        mnuOptions.add(mnuTheme);

        mnuSystem.add(mnuOptions);

        mnuIViewInformation.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        mnuIViewInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/businessman_find.png"))); // NOI18N
        mnuIViewInformation.setText("View Information");
        mnuIViewInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIViewInformationActionPerformed(evt);
            }
        });
        mnuSystem.add(mnuIViewInformation);
        mnuSystem.add(jSeparator1);

        mnuIExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        mnuIExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/exit.png"))); // NOI18N
        mnuIExit.setText("Exit");
        mnuIExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIExitActionPerformed(evt);
            }
        });
        mnuSystem.add(mnuIExit);

        mnuBSystem.add(mnuSystem);

        mnuHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/help.png"))); // NOI18N
        mnuHelp.setText("Help");

        mnuIHelpContent.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mnuIHelpContent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/help (2).png"))); // NOI18N
        mnuIHelpContent.setText("Help Contents");
        mnuHelp.add(mnuIHelpContent);

        mnuIAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        mnuIAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/images/about.png"))); // NOI18N
        mnuIAbout.setText("About");
        mnuIAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIAboutActionPerformed(evt);
            }
        });
        mnuHelp.add(mnuIAbout);

        mnuBSystem.add(mnuHelp);

        setJMenuBar(mnuBSystem);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuILoginSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuILoginSystemActionPerformed
        // TODO add your handling code here:
        dlgLogin login = new dlgLogin(this);
        login.setVisible(true);
    }//GEN-LAST:event_mnuILoginSystemActionPerformed

    private void mnuIAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIAboutActionPerformed
        // TODO add your handling code here:
        dlgAbount about = new dlgAbount(this, true);
        about.setVisible(true);
    }//GEN-LAST:event_mnuIAboutActionPerformed

    private void radioWindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioWindowsActionPerformed
        // TODO add your handling code here:
        if (radioWindows.isSelected()) {
            lookandfeel = guip.PLAF_WINDOWS;
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioWindowsActionPerformed

    private void radioMetalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMetalActionPerformed
        // TODO add your handling code here:
        if (radioMetal.isSelected()) {
            lookandfeel = guip.PLAF_METAL;
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioMetalActionPerformed

    private void radioNimbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNimbusActionPerformed
        // TODO add your handling code here:
        if (radioNimbus.isSelected()) {
            lookandfeel = guip.PLAF_NIMBUS;
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioNimbusActionPerformed

    private void menuIChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIChangePassActionPerformed
        // TODO add your handling code here:
        if (accCur != null) {
            dlgChangePass changePass = new dlgChangePass(this, true);
            changePass.setVisible(true);
        }
    }//GEN-LAST:event_menuIChangePassActionPerformed

    private void mnuIManagmentEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIManagmentEmpActionPerformed
        // TODO add your handling code here:
        frmEmployee employee = new frmEmployee();
        employee.setVisible(true);
    }//GEN-LAST:event_mnuIManagmentEmpActionPerformed

    private void mnuIHelpContentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIHelpContentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuIHelpContentActionPerformed

    private void mnuIExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mnuIExitActionPerformed

    private void mnuIViewInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIViewInformationActionPerformed
        // TODO add your handling code here:
        if (accCur != null) {
            PersonDAO personDao = new PersonDAO();
            Person person = personDao.readByID(this.accCur.getUsername());
            frmViewInfo viewInfo = new frmViewInfo(person);
            viewInfo.setVisible(true);
        }
    }//GEN-LAST:event_mnuIViewInformationActionPerformed

    private void mnuISwitchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuISwitchUserActionPerformed
        // TODO add your handling code here:
        if (this.accCur != null) {
            accCur = null;
            this.setVisible(false);
            dlgLogin login = new dlgLogin(this);
            login.setVisible(true);
        }
    }//GEN-LAST:event_mnuISwitchUserActionPerformed

    private void mnuILogoutSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuILogoutSystemActionPerformed
        // TODO add your handling code here:
        if (this.accCur != null) {
            accCur = null;
            this.setVisible(false);
            dlgLogin login = new dlgLogin(this);
            login.setVisible(true);
        }
    }//GEN-LAST:event_mnuILogoutSystemActionPerformed

    private void radioJgoodiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioJgoodiesActionPerformed
        // TODO add your handling code here:
        if (radioJgoodies.isSelected()) {
            lookandfeel = guip.PLAF_JGOODIES;
            guidao.setGUI(lookandfeel, theme);
        }
}//GEN-LAST:event_radioJgoodiesActionPerformed

    private void radioDarkStarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDarkStarActionPerformed
        // TODO add your handling code here:
        if (radioDarkStar.isSelected()) {
            theme = "DarkStar";
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioDarkStarActionPerformed

    private void radioDesertBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDesertBlueActionPerformed
        // TODO add your handling code here:
        if (radioDesertBlue.isSelected()) {
            theme = "DesertBlue";
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioDesertBlueActionPerformed

    private void radioDesertGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDesertGreenActionPerformed
        // TODO add your handling code here:
        if (radioDesertGreen.isSelected()) {
            theme = "DesertGreen";
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioDesertGreenActionPerformed

    private void radioDesertYellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDesertYellowActionPerformed
        // TODO add your handling code here:
        if (radioDesertYellow.isSelected()) {
            theme = "DesertYellow";
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioDesertYellowActionPerformed

    private void radioExperienceBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioExperienceBlueActionPerformed
        // TODO add your handling code here:
        if (radioExperienceBlue.isSelected()) {
            theme = "ExperienceBlue";
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioExperienceBlueActionPerformed

    private void radioExperienceGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioExperienceGreenActionPerformed
        // TODO add your handling code here:
        if (radioExperienceGreen.isSelected()) {
            theme = "ExperienceGreen";
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioExperienceGreenActionPerformed

    private void radioExperenceRoyaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioExperenceRoyaleActionPerformed
        // TODO add your handling code here:
        if (radioExperenceRoyale.isSelected()) {
            theme = "ExperienceRoyale";
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioExperenceRoyaleActionPerformed

    private void radioLightGrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioLightGrayActionPerformed
        // TODO add your handling code here:
        if (radioLightGray.isSelected()) {
            theme = "LightGray";
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioLightGrayActionPerformed

    private void radioSilverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSilverActionPerformed
        // TODO add your handling code here:
        if (radioSilver.isSelected()) {
            theme = "Silver";
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioSilverActionPerformed

    private void radioSkyBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSkyBlueActionPerformed
        // TODO add your handling code here:
        if (radioSkyBlue.isSelected()) {
            theme = "SkyBlue";
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioSkyBlueActionPerformed

    private void radioSkyBluerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSkyBluerActionPerformed
        // TODO add your handling code here:
        if (radioSkyBluer.isSelected()) {
            theme = "SkyBluer";
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioSkyBluerActionPerformed

    private void radioSkyGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSkyGreenActionPerformed
        // TODO add your handling code here:
        if (radioSkyGreen.isSelected()) {
            theme = "SkyGreen";
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioSkyGreenActionPerformed

    private void radioSkyPinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSkyPinkActionPerformed
        // TODO add your handling code here:
        if (radioSkyPink.isSelected()) {
            theme = "SkyPink";
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioSkyPinkActionPerformed

    private void radioSkyRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSkyRedActionPerformed
        // TODO add your handling code here:
        if (radioSkyRed.isSelected()) {
            theme = "SkyRed";
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioSkyRedActionPerformed

    private void radioSkyYellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSkyYellowActionPerformed
        // TODO add your handling code here:
        if (radioSkyYellow.isSelected()) {
            theme = "SkyYellow";
            guidao.setGUI(lookandfeel, theme);
        }
    }//GEN-LAST:event_radioSkyYellowActionPerformed

    public void isLogin() {
        if (this.accCur != null) {
            mnuILogoutSystem.setVisible(true);
            mnuISwitchUser.setVisible(true);
            mnuIViewInformation.setVisible(true);
            mnuILoginSystem.setVisible(false);
        } else {
            mnuILogoutSystem.setVisible(false);
            mnuISwitchUser.setVisible(false);
            mnuIViewInformation.setVisible(false);
            mnuILoginSystem.setVisible(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel StatusPnl;
    private javax.swing.ButtonGroup buttonGroupSkin;
    private javax.swing.ButtonGroup buttonGroupTheme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private com.jidesoft.swing.JideButton jideButton1;
    private com.jidesoft.swing.JideButton jideButton2;
    private javax.swing.JMenuItem menuIChangePass;
    private javax.swing.JMenuBar mnuBSystem;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenuItem mnuIAbout;
    private javax.swing.JMenuItem mnuIExit;
    private javax.swing.JMenuItem mnuIHelpContent;
    private javax.swing.JMenuItem mnuILoginSystem;
    private javax.swing.JMenuItem mnuILogoutSystem;
    private javax.swing.JMenuItem mnuISwitchUser;
    private javax.swing.JMenuItem mnuIViewInformation;
    private javax.swing.JMenu mnuOptions;
    private javax.swing.JMenu mnuSkin;
    private javax.swing.JMenu mnuSystem;
    private javax.swing.JMenu mnuTheme;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JPanel panelLogo;
    private javax.swing.JPanel panelRight;
    private javax.swing.JPanel pnlAccount;
    private javax.swing.JPanel pnlCertificate;
    private javax.swing.JPanel pnlCourse;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlMark;
    private javax.swing.JPanel pnlPayment;
    private javax.swing.JPanel pnlPermission;
    private javax.swing.JPanel pnlRegister;
    private javax.swing.JPanel pnlSubject;
    private javax.swing.JRadioButtonMenuItem radioDarkStar;
    private javax.swing.JRadioButtonMenuItem radioDesertBlue;
    private javax.swing.JRadioButtonMenuItem radioDesertGreen;
    private javax.swing.JRadioButtonMenuItem radioDesertYellow;
    private javax.swing.JRadioButtonMenuItem radioExperenceRoyale;
    private javax.swing.JRadioButtonMenuItem radioExperienceBlue;
    private javax.swing.JRadioButtonMenuItem radioExperienceGreen;
    private javax.swing.JRadioButtonMenuItem radioJgoodies;
    private javax.swing.JRadioButtonMenuItem radioLightGray;
    private javax.swing.JRadioButtonMenuItem radioMetal;
    private javax.swing.JRadioButtonMenuItem radioNimbus;
    private javax.swing.JRadioButtonMenuItem radioSilver;
    private javax.swing.JRadioButtonMenuItem radioSkyBlue;
    private javax.swing.JRadioButtonMenuItem radioSkyBluer;
    private javax.swing.JRadioButtonMenuItem radioSkyGreen;
    private javax.swing.JRadioButtonMenuItem radioSkyPink;
    private javax.swing.JRadioButtonMenuItem radioSkyRed;
    private javax.swing.JRadioButtonMenuItem radioSkyYellow;
    private javax.swing.JRadioButtonMenuItem radioWindows;
    private javax.swing.JToolBar tbMenu;
    private javax.swing.JTabbedPane tpnBusiness;
    // End of variables declaration//GEN-END:variables
}
