/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Hiaahsjas.java
 *
 * Created on Apr 2, 2011, 4:57:19 PM
 */
package com.hueic.CerGS.ui;

/**
 *
 * @author nhchung
 */
public class Hiaahsjas extends javax.swing.JFrame {

    /** Creates new form Hiaahsjas */
    public Hiaahsjas() {
        initComponents();
        pnlSubject subject = new pnlSubject();
        this.add(subject);
        this.setSize(860, 600);
        this.setVisible(true);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Hiaahsjas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
