/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Hiaahsjas.java
 *
 * Created on Apr 2, 2011, 4:57:19 PM
 */
package com.hueic.CerGS.ui;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author nhchung
 */
public class Hiaahsjas extends javax.swing.JFrame {

    /** Creates new form Hiaahsjas */
    public Hiaahsjas() {
        initComponents();
        try {
            copyImage("C:image1.png", "D:image1.png");
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
        //copy("C:/Users/nhchung/Desktop/Untitled.png", "/com/hueic/CerGS/avatar/Charge1.png");
        //pnlSubject subject = new pnlSubject();
//        SubjectDAO subjectDao = new SubjectDAO();
//
//        //JPanel report = new pnlCertificateReport("CPISM2");
//        JPanel report = new pnlSubjectReport(subjectDao.readByAll());
//        EmployeeDAO empDao = new EmployeeDAO();
//        JPanel report = new pnlEmployeeReport(empDao.readByAll());
//        this.add(report);
        // this.add(subject);
        this.setSize(860, 600);
        this.setVisible(true);

    }

    public void copy(String source, String destination) {
        FileInputStream fis = null;
        try {
            fis = new FileInputStream(new File(source));
            FileOutputStream fos = new FileOutputStream(new File(destination));
            int c;
            while ((c = fis.read()) != -1) {
                fos.write(c);
            }
        } catch (IOException ex) {
            Logger.getLogger(Hiaahsjas.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fis.close();
            } catch (IOException ex) {
                Logger.getLogger(Hiaahsjas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    public void copyImage(String source, String destination) {
        try {
            File sourceFile = new File(source);
            BufferedInputStream bis = new BufferedInputStream(new FileInputStream(sourceFile), 4096);
            // File targetFile = new File(destination);
            File targetFile = new File(destination);
            System.out.println("Sao the");
            //File targetFile = new File(getClass().getResource(destination));
            BufferedOutputStream bos = new BufferedOutputStream(new FileOutputStream(targetFile), 4096);
            System.out.println("Sao do nhi");
            int theChar;
            while ((theChar = bis.read()) != -1) {
                bos.write(theChar);
            }
            bos.close();
            bis.close();
            System.out.println("copy done!");

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hueic/CerGS/avatar/Charge.png"))); // NOI18N
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Hiaahsjas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
