/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddCustomer.java
 *
 * Created on May 10, 2010, 8:54:02 AM
 */
package com.hueic.CerGS.ui.main.scoure;

import com.hueic.CerGS.component.ColumnData;
import com.hueic.CerGS.component.ObjectTableModel;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JViewport;
import javax.swing.ListSelectionModel;
import javax.swing.ScrollPaneConstants;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author KISS
 */
public class frmView extends javax.swing.JDialog {

//    StaffBUZ buz = null;
    private ObjectTableModel tableModel;
    public ArrayList<Object> list = new ArrayList<Object>();
    // private ArrayList<Activities> filter = null;
    int comfirm = 0, id = 0;
    // Table's headers
    public JTable headerTable;
    // Index of the selected row
    public int index = -1;

    /** Creates new form AddCustomer */
    public frmView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
//        buz = new StaffBUZ();
        initComponents();
        loadtableStaff();
        setIconImage(new ImageIcon(getClass().getResource("/com/hueic/BugRS/ui/system/magician.png")).getImage());
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(frmView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(frmView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(frmView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void loadtable() {
        ColumnData[] columns = {
            new ColumnData("UserName", 100, SwingConstants.LEFT, 7),
            new ColumnData("FirstName", 100, SwingConstants.LEFT, 2),
            new ColumnData("LastName", 100, SwingConstants.LEFT, 3),
            new ColumnData("Address", 120, SwingConstants.LEFT, 4),
            new ColumnData("Email", 50, SwingConstants.LEFT, 5),};

        tableModel = new ObjectTableModel(tblStaff, columns, list);
        headerTable = tableModel.getHeaderTable();

        // Create numbering column
        headerTable.createDefaultColumnsFromModel();
        tblStaff.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        // Put it in a viewport that we can control a bit
        JViewport viewport = new JViewport();

        // Display numbering column
        viewport.setView(headerTable);
        viewport.setPreferredSize(headerTable.getMaximumSize());

        scr.setRowHeader(viewport);
        scr.setCorner(ScrollPaneConstants.UPPER_LEFT_CORNER, headerTable.getTableHeader());
    }

    public void loadtableStaff() {
        //list = buz.findByAll();
        loadtable();
    }

    public void loadtableCentre() {
        //list = buz.findByCallCentre();
        loadtable();
    }

    public void loadtableAcount() {
       // list = buz.findByAccount();
        loadtable();
    }

    public void loadtableDispathcer() {
      //  list = buz.findByDispatcher();
        loadtable();
    }

    public void loadtableAdmin() {
       // list = buz.findByAdmin();
        loadtable();
    }

    public void loadStaff() {
//        StaffDTO staff = list.get(tblStaff.getSelectedRow());
//        DetailsStaff de = new DetailsStaff(this, true);
//        de.setStaff(staff);
//        de.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDepartment = new javax.swing.JPanel();
        cbDepartment = new javax.swing.JComboBox();
        pnlStaff = new javax.swing.JPanel();
        scr = new javax.swing.JScrollPane();
        tblStaff = new javax.swing.JTable();
        pnlButton = new javax.swing.JPanel();
        btnDetailsStaff = new javax.swing.JButton();
        btnAddStaff = new javax.swing.JButton();
        btnEditStaff = new javax.swing.JButton();
        btnDeleteStaff = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlDepartment.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Department", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(0, 0, 204))); // NOI18N

        cbDepartment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All Department", "Call Centre", "Account", "Dispatcher & Order", "Administrator" }));
        cbDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDepartmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDepartmentLayout = new javax.swing.GroupLayout(pnlDepartment);
        pnlDepartment.setLayout(pnlDepartmentLayout);
        pnlDepartmentLayout.setHorizontalGroup(
            pnlDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDepartmentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(361, Short.MAX_VALUE))
        );
        pnlDepartmentLayout.setVerticalGroup(
            pnlDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDepartmentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlStaff.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Staff", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(0, 0, 204))); // NOI18N
        pnlStaff.setLayout(new java.awt.BorderLayout());

        tblStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStaffMouseClicked(evt);
            }
        });
        scr.setViewportView(tblStaff);

        pnlStaff.add(scr, java.awt.BorderLayout.CENTER);

        btnDetailsStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user1.png"))); // NOI18N
        btnDetailsStaff.setText("Staff Details");
        btnDetailsStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsStaffActionPerformed(evt);
            }
        });
        pnlButton.add(btnDetailsStaff);

        btnAddStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/view.png"))); // NOI18N
        btnAddStaff.setText("Add Staff");
        btnAddStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStaffActionPerformed(evt);
            }
        });
        pnlButton.add(btnAddStaff);

        btnEditStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/edit.png"))); // NOI18N
        btnEditStaff.setText("Edit Staff");
        btnEditStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditStaffActionPerformed(evt);
            }
        });
        pnlButton.add(btnEditStaff);

        btnDeleteStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete.png"))); // NOI18N
        btnDeleteStaff.setText("Delete Staff");
        btnDeleteStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteStaffActionPerformed(evt);
            }
        });
        pnlButton.add(btnDeleteStaff);

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cancel-2-16x16.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        pnlButton.add(btnCancel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246)
                .addComponent(pnlButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(75, Short.MAX_VALUE)
                    .addComponent(pnlStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(67, 67, 67)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStaffActionPerformed
//        AddStaff dlg = new AddStaff(this, true);
//        dlg.setSize(400, 600);
//        dlg.setLocationRelativeTo(null);
//        dlg.setVisible(true);
    }//GEN-LAST:event_btnAddStaffActionPerformed

    private void btnEditStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditStaffActionPerformed
        loadStaff();
    }//GEN-LAST:event_btnEditStaffActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void cbDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDepartmentActionPerformed

        if (cbDepartment.getSelectedIndex() == 0) {
            loadtableStaff();
            headerTable.updateUI();
            tblStaff.updateUI();
        } else if (cbDepartment.getSelectedIndex() == 1) {
            loadtableCentre();
            headerTable.updateUI();
            tblStaff.updateUI();
        } else if (cbDepartment.getSelectedIndex() == 2) {
            loadtableAcount();
            headerTable.updateUI();
            tblStaff.updateUI();
        } else if (cbDepartment.getSelectedIndex() == 3) {
            loadtableDispathcer();
            headerTable.updateUI();
            tblStaff.updateUI();
        } else {
            loadtableAdmin();
            headerTable.updateUI();
            tblStaff.updateUI();
        }
    }//GEN-LAST:event_cbDepartmentActionPerformed

    private void btnDetailsStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsStaffActionPerformed
        loadStaff();
    }//GEN-LAST:event_btnDetailsStaffActionPerformed

    private void btnDeleteStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteStaffActionPerformed
//        int confirm = 0;
//        confirm = JOptionPane.showConfirmDialog(this, "Do you want to dedete staff ?", "Delete Staff", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, null);
//        if (confirm == JOptionPane.YES_OPTION) {
//            int index2 = tblStaff.getSelectedRow();
//            if (index2 == -1) {
//            } else {
////                StaffDTO staff = list.get(index2);
//                if (staff.getUserName().equalsIgnoreCase("admin")) {
//                    JOptionPane.showMessageDialog(this, "Can't remove Super Admin");
//                } else {
//                    buz.remove(staff);
//                    list.remove(index2);
//                    headerTable.updateUI();
//                    tblStaff.updateUI();
//                }
//
//            }
//        }

    }//GEN-LAST:event_btnDeleteStaffActionPerformed

    private void tblStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStaffMouseClicked
        if (evt.getClickCount() == 2) {
            loadStaff();
        }
    }//GEN-LAST:event_tblStaffMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                frmView dialog = new frmView(null, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStaff;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDeleteStaff;
    private javax.swing.JButton btnDetailsStaff;
    private javax.swing.JButton btnEditStaff;
    private javax.swing.JComboBox cbDepartment;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JPanel pnlDepartment;
    private javax.swing.JPanel pnlStaff;
    private javax.swing.JScrollPane scr;
    public javax.swing.JTable tblStaff;
    // End of variables declaration//GEN-END:variables
}
