/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pnlCertificate.java
 *
 * Created on Apr 2, 2011, 3:41:08 AM
 */
package com.hueic.CerGS.ui.report;

import com.hueic.CerGS.component.report.CertificateReportManager;
import com.hueic.CerGS.dao.CertificateDAO;
import com.hueic.CerGS.dao.MarkDAO;
import com.hueic.CerGS.dao.RegisterDAO;
import com.hueic.CerGS.entity.Certificate;
import javax.swing.JOptionPane;

/**
 *
 * @author nhchung
 */
public class pnlCertificate extends javax.swing.JPanel {

    private int certificateId;
    private String courseId;
    private MarkDAO markDAO;
    private RegisterDAO registerDAO;
    private CertificateDAO cerDAO;
    private Certificate cer;
    private CertificateReportManager cerReportManager;

    /** Creates new form pnlCertificate */
    public pnlCertificate() {
        initComponents();
        this.certificateId = certificateId;
        registerDAO = new RegisterDAO();
        cerDAO = new CertificateDAO();
        cer = cerDAO.readById(this.certificateId);
        markDAO = new MarkDAO();
        courseId = registerDAO.readByStudentId(cer.getStudentID()).getCourseId();
        cerReportManager = new CertificateReportManager();

        try {
            this.add(cerReportManager.getPanelViewer(true));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.toString(), "Report Message", JOptionPane.ERROR_MESSAGE);
        }
        this.setSize(860, 580);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
